import {dataLessons,dataGlossary} from './data-curriculum.js';
const task=(id,title,prompt,starter,answer,expected,test,hints,explain,kind='基础练习')=>({id,title,prompt,starter,answer,expected,test,hints,explain,kind});
const quiz=(id,prompt,options,correct,explain)=>({id,prompt,options,correct,explain});
export const lessons=[
{
 id:'hello',title:'让电脑说第一句话',short:'第一行代码',chapter:'01',track:'python',stage:'起步',minutes:10,file:'hello.py',
 lead:'认识 print()，亲手运行、修改，然后看到自己的结果。',goals:['让程序输出一句文字','修改示例，并解释变化的结果'],
 concept:'print() 会把括号里的内容显示出来。括号内的文字用引号包起来，表示一段字符串。以 # 开头的内容叫注释，用来解释代码，不会被执行。',
 analogy:'print() 就像一个小喇叭。你把要说的话放进括号，它就帮你说出来。注释像贴在喇叭旁边的使用说明。',
 code:'# 让电脑说一句话\nprint("你好，世界！")',expected:'你好，世界！',
 pitfall:'引号和括号要成对出现，并使用英文符号。输入法里的中文引号 “ ” 不能代替代码中的英文引号。',
 steps:['先读代码，猜猜屏幕上会出现什么。','点击右侧「运行代码」，对照预期输出。','把「世界」换成你的名字，再运行一次。'],
 summary:['print()：输出括号里的内容','"文字"：表示字符串','#：注释，用来给人解释代码'],
 diagram:['一段文字','print()','屏幕上的结果'],terms:['字符串','注释','输出'],
 tasks:[
 task('hello-name','改一句问候','让程序只输出：你好，小林！','# 把问候对象换成小林\nprint("你好，世界！")','# 输出自己的问候\nprint("你好，小林！")','你好，小林！','assert output.strip() == "你好，小林！", "请检查文字和标点：你好，小林！"',['只需要修改引号里面的内容。','保留 print() 和英文引号。','把「世界」改为「小林」。'],'程序结构没有变化，变化的是交给 print() 的文字。'),
 task('hello-two','两行自我介绍','依次输出两行：我是小林 / 我正在学 Python。','# 先写姓名，再写正在做的事\nprint("我是小林")','# 两条语句按顺序执行\nprint("我是小林")\nprint("我正在学 Python。")','我是小林\n我正在学 Python。','assert output.strip() == "我是小林\\n我正在学 Python。", "需要两行，顺序是姓名、学习内容。"',['每个 print() 默认输出后换行。','你需要两条 print() 语句。','在现有语句下面添加 print("我正在学 Python。")。'],'代码从上到下执行，第二条 print() 会显示在新的一行。','综合练习'),
 task('hello-comment','注释也会被说出来吗','写一行注释「今天开始学编程」，然后只输出：出发！','# 今天开始学编程\n','# 今天开始学编程\nprint("出发！")','出发！','assert output.strip() == "出发！", "注释不应出现在输出中，只输出：出发！"',['# 开头的内容不会运行。','输出文字仍然需要 print()。','在注释下方添加 print("出发！")。'],'注释是给人看的说明。试着改掉注释，程序结果不会改变。','选做挑战')],
 quizzes:[quiz('hello-q1','哪一部分会出现在实际输出中？',['# 打招呼','print("你好") 中的「你好」','print 这个单词本身'],1,'print() 输出括号里的文字；注释和函数名不会自动输出。'),quiz('hello-q2','为什么代码里的引号要成对出现？',['标记文字从哪里开始、在哪里结束','让输出变成两行','让程序运行更快'],0,'引号划定字符串的边界，漏掉一边，Python 就不知道文字在哪里结束。')]
},
{
 id:'variables',title:'给数据取一个名字',short:'变量与赋值',chapter:'02',track:'python',stage:'起步',minutes:12,file:'profile.py',
 lead:'用变量记住你的名字，让同一份数据可以反复使用。',goals:['创建并打印一个变量','解释重新赋值后，输出为什么变化'],
 concept:'变量是用来关联数据对象的名字。name = "小林" 表示把右边的字符串交给左边的名字。之后写 name，就能使用这份数据。',analogy:'你可以把变量理解成贴在数据上的名字标签。重新赋值，就是把这个标签贴到新的数据上。',
 code:'# 给数据贴上名字标签\nname = "小林"\ndays = 3\nprint(name, days)\ndays = 4\nprint(name, days)',expected:'小林 3\n小林 4',
 pitfall:'name 和 Name 是两个不同的名字。print(name) 使用变量，print("name") 输出的是 name 这几个字母。',steps:['运行示例，观察 days 的两次输出。','把 name 的值换成你的名字。','把第二次赋值改成 days = 10，再运行。'],summary:['变量：为数据提供名字','=：先得到右边的值，再关联到左边的名字','重新赋值：更新名字关联的对象'],diagram:['days = 3','days 关联 3','days = 4 后关联 4'],terms:['变量','赋值','对象'],
 tasks:[
 task('var-city','保存你的城市','创建 city 变量，保存「杭州」，并打印它。','# 创建城市变量\ncity = ""\nprint(city)','# 保存并使用变量\ncity = "杭州"\nprint(city)','杭州','assert scope.get("city") == "杭州" and output.strip() == "杭州", "city 应保存字符串杭州，并把它打印出来。"',['文字需要英文引号。','把空字符串替换为城市名。','city = "杭州"。'],'变量名不加引号，赋给它的文字需要引号。'),
 task('var-profile','我的学习名片','创建 name = "小林"、days = 7，然后在一行中打印两者。','# 保存姓名和天数\nname = "小林"\ndays = 0\n','# 一张简单的名片\nname = "小林"\ndays = 7\nprint(name, days)','小林 7','assert scope.get("name") == "小林" and type(scope.get("days")) is int and scope["days"] == 7 and output.strip() == "小林 7", "请保存姓名和整数天数，再用 print(name, days) 输出。"',['天数是数字，不需要引号。','print() 里可以用逗号分隔两个值。','把 days 改成 7，添加 print(name, days)。'],'print() 用逗号接收多个值时，默认用空格分隔。','综合练习'),
 task('var-copy','两个名字会一直联动吗','先运行，观察输出；再解释为什么 b 没有变。','# 观察赋值后的关系\na = 3\nb = a\na = 4\nprint(a, b)','# b 仍然关联整数 3\na = 3\nb = a\na = 4\nprint(a, b)','4 3','assert output.strip() == "4 3", "先保留示例运行，观察结果 4 3。"',['b = a 使用的是此时 a 关联的值。','之后重新给 a 赋值，不会自动改变 b。','输出是 4 3；不是 4 4。'],'一开始两个名字都关联 3，之后只有 a 改为关联 4。','选做挑战')],
 quizzes:[quiz('var-q1','name = "小林" 后，print("name") 输出什么？',['小林','name','报错'],1,'带引号的是文字本身。想使用变量，应写 print(name)。'),quiz('var-q2','读取一个还没有赋值的变量，通常会遇到什么？',['NameError：找不到名字','自动得到 0','自动得到空字符串'],0,'Python 不会替你猜变量值。检查拼写，并先给变量赋值。')]
},
{
 id:'types',title:'数字和文字，不是一回事',short:'类型与转换',chapter:'03',track:'python',stage:'起步',minutes:15,file:'types.py',
 lead:'识别四种常见类型，把数字文字转换成真正的数字。',goals:['区分整数、浮点数、字符串和布尔值','使用 int()、float() 转换数字文字'],concept:'类型说明一个值属于哪一类。int 是整数，float 是浮点数，str 是字符串，bool 表示真假。使用 type(值) 可以查看类型。数字加上引号后，就是文字。',analogy:'表单里的「姓名」和「学习天数」是不同栏目。即使天数写成 "7"，它也仍是文字，需要先转换才能当数字计算。',
 code:'# 查看类型，再转换数字文字\ndays_text = "7"\ndays = int(days_text)\nhours = float("1.5")\nready = True\nprint(type(days_text))\nprint(type(days))\nprint(hours, ready)',expected:"<class 'str'>\n<class 'int'>\n1.5 True",pitfall:'True 首字母大写。int("1.5") 会报错；需要小数时使用 float()。int(1.9) 得到 1，不是四舍五入。',steps:['先比较 "7" 和 7 的类型。','把时长文字改成 "2.5"，重新运行。','试一次 int("十二")，阅读报错，再恢复正确数据。'],summary:['int / float：整数与浮点数','str / bool：文字与真假','type() 看类型；int()、float()、str() 做转换'],diagram:['"7" · 字符串','int("7")','7 · 整数'],terms:['类型','字符串','布尔值'],
 tasks:[
 task('type-float','把文字变成小数','将 "2.5" 转换为浮点数 hours，打印 hours。','# 把文字转成小数\nhours = "2.5"\nprint(hours)','# float() 返回浮点数\nhours = float("2.5")\nprint(hours)','2.5','assert type(scope.get("hours")) is float and scope["hours"] == 2.5, "输出一样不代表类型一样；hours 必须是 float。"',['需要使用 float()。','把文字作为 float() 的参数。','hours = float("2.5")。'],'本题同时检查值和类型，直接输出字符串虽然看起来一样，但没有完成转换。'),
 task('type-profile','升级学习档案','保存 name = "小林"、days = int("7")、hours = float("1.5")、ready = True，在一行打印四个变量。','# 先保存姓名\nname = "小林"\n','# 档案里有不同类型\nname = "小林"\ndays = int("7")\nhours = float("1.5")\nready = True\nprint(name, days, hours, ready)','小林 7 1.5 True','assert scope.get("name") == "小林" and type(scope.get("days")) is int and scope["days"] == 7 and type(scope.get("hours")) is float and scope["hours"] == 1.5 and scope.get("ready") is True and output.strip() == "小林 7 1.5 True", "检查四个值及其类型，并按顺序输出。"',['天数、时长、准备状态的类型各不相同。','ready 的值不加引号。','打印时使用 print(name, days, hours, ready)。'],'综合使用字符串、整数、浮点数和布尔值。','综合练习'),
 task('type-negative','截断与四舍五入','打印 int(2.9) 和 int(-2.9)，比较结果。','# 先猜结果，再运行\nprint(int(2.9))\nprint(int(-2.9))','# 转换会向零截断\nprint(int(2.9))\nprint(int(-2.9))','2\n-2','assert output.strip() == "2\\n-2", "观察向零截断：2 和 -2。"',['两个结果都更靠近零。','正数和负数都丢掉小数部分。','结果依次是 2 和 -2。'],'这里是向零截断，不能把 int() 当成四舍五入函数。','选做挑战')],
 quizzes:[quiz('type-q1','"False" 属于哪种类型？',['bool','str','int'],1,'引号里是字符串，不会因为内容是 False 就变成布尔值。'),quiz('type-q2','哪一种能成功得到整数 12？',['int("12.5")','str(12)','int("12")'],2,'整数形式的字符串可以交给 int()；str(12) 得到的是文字。')]
},
{
 id:'input',title:'让程序听见你的回答',short:'输入与计算',chapter:'04',track:'python',stage:'会交互',minutes:15,file:'greeting.py',lead:'接收输入，转换类型，算出一个与你有关的结果。',goals:['使用 input() 接收文字','转换输入后进行简单计算'],concept:'input() 会读取一行输入，返回字符串。要进行加减乘除，先把数字文字转换成数字。+ 表示加法，* 表示乘法；print() 可以输出计算结果。',analogy:'input() 像一张等你填写的表单。你填的「20」最初是一段文字，int() 帮你把它变成可以计算的整数。',
 code:'# 输入区提前填好：小林、20（分两行）\nname = input("你叫什么名字？")\nage = int(input("你几岁？"))\nprint("你好", name)\nprint("明年你", age + 1, "岁")',stdin:'小林\n20',expected:'你叫什么名字？你几岁？你好 小林\n明年你 21 岁',pitfall:'input() 返回字符串。在本网站运行前，请在「程序输入」里按读取顺序每行填一个答案；提示文字不自动换行。',steps:['先在输入区填两行：姓名、年龄。','运行，确认年龄增加了 1。','改成另一组输入，验证程序无需改代码。'],summary:['input()：读取一行文字','int(input())：读取并转换成整数','+、-、*、/：加减乘除'],diagram:['输入 "20"','int() 转换','20 + 1 得到 21'],terms:['输入','字符串','解释器'],
 tasks:[
 task('input-next','算出明年的年龄','读取一行年龄，将其转换为整数 age，输出 age + 1。输入区填 20。','# 读取年龄后计算\nage = input()\nprint(age)','# 数字文字先转换\nage = int(input())\nprint(age + 1)','21','assert type(scope.get("age")) is int and output.strip() == str(scope["age"] + 1), "age 必须是整数，输出它加 1 后的结果。"',['input() 得到的不是整数。','使用 int(input())。','最后写 print(age + 1)。'],'题目会根据你的实际输入检查计算结果。'),
 task('input-hours','每周学习计划','依次读取每天分钟数 minutes 和每周天数 days，都是整数。打印两者乘积。输入区填两行：15、5。','# 一行读取一个数字\nminutes = int(input())\n','# 计算每周总分钟数\nminutes = int(input())\ndays = int(input())\nprint(minutes * days)','75','assert type(scope.get("minutes")) is int and type(scope.get("days")) is int and output.strip() == str(scope["minutes"] * scope["days"]), "读取两个整数，并输出乘积。"',['输入区要有两行。','第二个变量也需要 int() 转换。','用 print(minutes * days) 输出总数。'],'输入、转换、计算组成了一个能处理不同数据的程序。','综合练习'),
 task('input-repeat','文字也能乘吗','输出字符串 "加油 " 重复 3 次的结果。','# 试试字符串乘以整数\n','# 重复文字\nprint("加油 " * 3)','加油 加油 加油','assert output.strip() == "加油 加油 加油", "在文字末尾留一个空格，再重复三次。"',['字符串乘以整数会重复。','保留文字末尾的空格。','print("加油 " * 3)。'],'同一个运算符遇到不同类型，行为可能不同。','选做挑战')],quizzes:[quiz('input-q1','input() 默认返回什么？',['整数','字符串','布尔值'],1,'即使输入的是 20，也先得到字符串 "20"。'),quiz('input-q2','每天 15 分钟，学习 5 天，应该用什么运算？',['15 + 5','15 * 5','15 / 5'],1,'重复五份相同时间，可以用乘法计算总数。')]
},
{
 id:'conditions',title:'让程序做一个小决定',short:'条件判断',chapter:'05',track:'python',stage:'会交互',minutes:15,file:'decision.py',lead:'使用 if / else，根据不同情况给出不同回应。',goals:['写出带缩进的 if / else','使用边界数据验证条件'],concept:'if 后面写条件，条件成立时执行其下方缩进的代码；否则执行 else 下的代码。>= 表示大于等于，== 表示是否相等。注意 = 是赋值。',analogy:'就像出门前看天气：如果下雨，就带伞；否则，直接出门。程序需要你把这个分岔口说清楚。',code:'# 根据学习时长给出建议\nminutes = 15\nif minutes >= 15:\n    print("完成今天的小任务")\nelse:\n    print("先复习一个知识点")',expected:'完成今天的小任务',pitfall:'if 和 else 后有冒号，内部语句需要一致缩进。建议每层 4 个空格。不要把比较的 == 写成赋值的 =。',steps:['运行 minutes = 15，观察走哪条分支。','改为 10，再运行。','改为 16，确认边界两侧的行为。'],summary:['if：条件成立时执行','else：条件不成立时执行','冒号与缩进：标记属于这个分支的代码'],diagram:['minutes >= 15？','是：完成小任务','否：复习知识点'],terms:['条件','缩进','边界'],
 tasks:[
 task('if-score','判断是否达标','score = 60，大于等于 60 输出「达标」，否则输出「继续练习」。','# 在这里写条件\nscore = 60\n','# 检查分数\nscore = 60\nif score >= 60:\n    print("达标")\nelse:\n    print("继续练习")','达标','assert output.strip() == ("达标" if scope.get("score",0) >= 60 else "继续练习"), "检查条件是否包含刚好 60 的情况。"',['条件是 score >= 60。','两个分支分别输出不同文字。','注意冒号和 4 个空格缩进。'],'60 恰好位于边界，>= 会把它包含在内。'),
 task('if-plan','根据输入推荐任务','读取整数 minutes。至少 15 分钟输出「做一个新任务」，否则输出「复习错题」。输入区填 10。','# 读取今天可用的分钟数\nminutes = int(input())\n','# 根据可用时间选择任务\nminutes = int(input())\nif minutes >= 15:\n    print("做一个新任务")\nelse:\n    print("复习错题")','复习错题','assert type(scope.get("minutes")) is int and output.strip() == ("做一个新任务" if scope["minutes"] >= 15 else "复习错题"), "读取分钟数，然后选择对应分支。"',['先完成输入转换。','以 15 为界分成两种情况。','分别用 10、15、20 验证。'],'单次通过只验证当前输入。完成后还要自己测试另一条分支。','综合练习'),
 task('if-bug','修复一个边界错误','这个程序在 score = 60 时输出错了。只修改条件，让 60 也达标。','# 找出条件里的问题\nscore = 60\nif score > 60:\n    print("达标")\nelse:\n    print("继续练习")','# 包含边界值\nscore = 60\nif score >= 60:\n    print("达标")\nelse:\n    print("继续练习")','达标','assert output.strip() == "达标", "刚好 60 也应该达标，检查比较符号。"',['> 不包括等于。','需求说的是大于或等于。','把 > 改成 >=。'],'程序能运行，但结果不符合需求，属于逻辑错误。','选做挑战')],quizzes:[quiz('if-q1','哪个符号表示判断两个值是否相等？',['=','==','>='],1,'= 用于赋值，== 用于相等比较。'),quiz('if-q2','if score >= 60 时，哪个值最适合检查边界？',['100','60','1000'],1,'边界值最容易暴露 > 与 >= 混淆。')]
},
{
 id:'loops',title:'把重复的事交给电脑',short:'循环与重复',chapter:'06',track:'python',stage:'会组织',minutes:15,file:'repeat.py',lead:'用 for 和 range()，让同一段代码重复执行。',goals:['用循环完成重复输出','理解 range() 的结束值不包含在结果里'],concept:'for 循环会依次取出一组值，执行缩进中的代码。range(1, 4) 提供 1、2、3，不包括 4。循环变量每次会得到一个新值。',analogy:'就像老师按名单点名，每次拿到一个名字，执行同一个动作，直到名单结束。',code:'# 记录三天的学习\nfor day in range(1, 4):\n    print("第", day, "天，继续练习")',expected:'第 1 天，继续练习\n第 2 天，继续练习\n第 3 天，继续练习',pitfall:'range(1, 4) 不包含 4。缩进决定哪些语句会重复，退出缩进后的语句只在循环结束后执行。',steps:['预测会打印几行，再运行。','把结束值改为 6，检查最后一天。','在循环外添加 print("完成")，观察顺序。'],summary:['for：逐个取值并执行','range(起点, 终点)：包含起点，不包含终点','缩进：决定循环内部的动作'],diagram:['取出下一个值','执行缩进内代码','还有值就继续'],terms:['循环','缩进','边界'],
 tasks:[
 task('loop-count','数到五','使用 for 循环，逐行输出 1 到 5。','# 让循环输出 1 到 5\n','# 终点不包括 6\nfor number in range(1, 6):\n    print(number)','1\n2\n3\n4\n5','assert output.strip() == "1\\n2\\n3\\n4\\n5", "应有五行，从 1 到 5。"',['range() 的终点不包含。','需要 range(1, 6)。','在循环里缩进写 print(number)。'],'选择终点时，要比最后一个需要的整数大 1。'),
 task('loop-total','算一周的练习数','每天做 2 题，共 5 天。使用 total 从 0 开始，在循环中累加 2，最后打印 total。','# 用变量累计结果\ntotal = 0\n','# 五次累加\ntotal = 0\nfor day in range(5):\n    total = total + 2\nprint(total)','10','assert scope.get("total") == 10 and output.strip() == "10", "从 0 开始累加五次 2，最后在循环外打印 10。"',['range(5) 提供 0 到 4，共五个值。','每次更新 total = total + 2。','最后的 print(total) 不缩进。'],'变量保存累计结果，循环执行重复更新，循环外只输出一次。','综合练习'),
 task('loop-empty','一次也不执行？','运行 range(3, 3) 的循环，再在循环外输出「结束」。','# 起点与终点相同\nfor n in range(3, 3):\n    print(n)\nprint("结束")','# 这个范围没有任何值\nfor n in range(3, 3):\n    print(n)\nprint("结束")','结束','assert output.strip() == "结束", "range(3, 3) 为空，只执行循环外的输出。"',['终点不包含。','起点就是终点，没有可取的值。','循环体零次执行。'],'循环并不保证至少执行一次，要根据数据范围判断。','选做挑战')],quizzes:[quiz('loop-q1','range(1, 4) 会提供几个整数？',['3 个','4 个','5 个'],0,'提供 1、2、3，共三个。'),quiz('loop-q2','想让一行代码在循环结束后只执行一次，应该怎么办？',['再缩进一层','放到循环后，取消循环体那层缩进','删掉所有缩进'],1,'只取消循环体的那层缩进，使它不再属于循环。')]
},
{
 id:'lists',title:'用一个列表，装下许多任务',short:'列表与字典',chapter:'07',track:'python',stage:'会组织',minutes:18,file:'tasks.py',lead:'保存一组任务，添加新任务，再逐个展示。',goals:['创建列表、添加元素、按索引读取','理解字典用名字查找信息'],concept:'列表用方括号保存一组有顺序的值，索引从 0 开始。append() 在末尾添加一个元素。字典用键关联值，例如 {"name": "小林"}，再用 profile["name"] 读取。',analogy:'列表像按顺序排好的储物格，第一格的编号是 0。字典像通讯录，用姓名这样的键查找对应信息。',code:'# 保存并展示任务\ntasks = ["读例子", "改代码"]\ntasks.append("做练习")\nprint(tasks[0])\nfor task in tasks:\n    print(task)\nprofile = {"name": "小林"}\nprint(profile["name"])',expected:'读例子\n读例子\n改代码\n做练习\n小林',pitfall:'长度为 3 的列表，索引是 0、1、2。tasks[3] 会越界。列表读取靠位置，字典读取靠键，不要混淆。',steps:['先看第一项为什么用 tasks[0]。','添加一个新任务，再运行循环。','修改字典中的姓名，观察最后一行。'],summary:['列表 []：有顺序的一组值','append()：在末尾加一个元素','字典 {}：按键找到对应的值'],diagram:['索引 0：读例子','索引 1：改代码','索引 2：做练习'],terms:['列表','索引','字典'],
 tasks:[
 task('list-first','找到第一项','创建列表 colors = ["蓝", "橙"]，打印第一项。','# 索引从哪里开始？\ncolors = ["蓝", "橙"]\n','# 第一项的索引是 0\ncolors = ["蓝", "橙"]\nprint(colors[0])','蓝','assert scope.get("colors") == ["蓝","橙"] and output.strip() == "蓝", "使用索引 0 读取第一项。"',['第一项不是索引 1。','使用 colors[0]。','print(colors[0])。'],'从零开始编号是一种约定。'),
 task('list-tasks','搭建待办清单','创建 tasks，已有「读书」「练习」，添加「复习」，再用循环逐行输出全部任务。','# 初始任务\ntasks = ["读书", "练习"]\n','# 添加并遍历\ntasks = ["读书", "练习"]\ntasks.append("复习")\nfor task in tasks:\n    print(task)','读书\n练习\n复习','assert scope.get("tasks") == ["读书","练习","复习"] and output.strip() == "读书\\n练习\\n复习", "列表中应有三项，按顺序逐行输出。"',['先 append()，再循环。','for task in tasks 会每次取出一个任务。','把 print(task) 放到循环内部。'],'列表保存数据，循环负责统一处理每一项。','综合练习'),
 task('dict-profile','按名字找信息','创建 profile 字典，name 是「小林」，days 是 7，打印 days 对应的值。','# 用键组织信息\n','# 字典通过键读取\nprofile = {"name": "小林", "days": 7}\nprint(profile["days"])','7','assert scope.get("profile") == {"name":"小林","days":7} and output.strip() == "7", "days 是字符串键，对应值为整数 7。"',['字典使用大括号。','键和值之间用冒号。','用 profile["days"] 读取天数。'],'字典的键可以明确表达数据含义。','选做挑战')],quizzes:[quiz('list-q1','列表第一项的索引是？',['0','1','-2'],0,'正向索引从 0 开始。'),quiz('list-q2','tasks.append("复习") 做了什么？',['清空列表','添加一个末尾元素','读取第一项'],1,'append() 会修改原列表，添加一个元素。')]
},
{
 id:'functions',title:'把常用动作，装进一个函数',short:'函数与返回值',chapter:'08',track:'python',stage:'会组织',minutes:18,file:'functions.py',lead:'给一组操作取名字，需要时调用它。',goals:['定义带参数的函数并调用','区分 return 与 print()'],concept:'def 用来定义函数。参数是调用时传入的数据，return 把结果交还给调用者。定义函数不会立刻执行函数内部代码，需要通过函数名和括号调用。',analogy:'函数像一台有名字的小机器。参数是原料，return 是机器交给你的成品。print() 只是把信息显示在屏幕上。',code:'# 定义一台计算小机器\ndef weekly_minutes(minutes, days):\n    return minutes * days\n\ntotal = weekly_minutes(15, 5)\nprint(total)',expected:'75',pitfall:'只定义函数不会得到输出。return 和 print() 不同：前者返回数据，后者显示信息。没有 return 的函数默认返回 None。',steps:['找到函数名、两个参数和返回值。','把调用改为 weekly_minutes(20, 3)。','调用两次，比较结果。'],summary:['def：定义函数','参数：调用时输入的数据','return：把结果交还调用者'],diagram:['输入 minutes、days','函数内部计算','return 返回结果'],terms:['函数','参数','返回值'],
 tasks:[
 task('fn-double','写一个翻倍函数','定义 double(number)，返回 number * 2，再打印 double(4)。','# 把参数翻倍\ndef double(number):\n    return number\n\nprint(double(4))','# 返回计算结果\ndef double(number):\n    return number * 2\n\nprint(double(4))','8','assert callable(scope.get("double")) and scope["double"](4) == 8 and scope["double"](7) == 14 and output.strip() == "8", "函数需要对不同输入都能翻倍。"',['改的是 return 后的表达式。','不要把返回值写死成 8。','return number * 2。'],'本题会用 4 和 7 检查函数，确保它处理参数而不是固定输出。'),
 task('fn-plan','可复用的学习计划','定义 plan(minutes, days)，返回总时长；分别打印 plan(15, 5) 和 plan(20, 3)。','# 定义后再调用\n','# 同一个函数使用两组参数\ndef plan(minutes, days):\n    return minutes * days\n\nprint(plan(15, 5))\nprint(plan(20, 3))','75\n60','assert callable(scope.get("plan")) and scope["plan"](15,5) == 75 and scope["plan"](20,3) == 60 and scope["plan"](2,4) == 8 and output.strip() == "75\\n60", "检查函数返回值和两次输出，不要把结果写死。"',['函数只有一份，调用可以有多次。','形参写 minutes, days。','函数外写两次 print(plan(...))。'],'函数将计算逻辑集中在一个地方，方便复用与修改。','综合练习'),
 task('fn-return','修复只有打印的函数','修复函数，让 result 得到 6，且程序只输出一行 6。','# 这里把打印和返回混淆了\ndef double(number):\n    print(number * 2)\n\nresult = double(3)\nprint(result)','# 返回数据，再由调用者打印\ndef double(number):\n    return number * 2\n\nresult = double(3)\nprint(result)','6','assert scope.get("result") == 6 and output.strip() == "6", "函数内部应返回结果，不要只打印。"',['先运行错误版本，观察 None。','print() 没有把计算结果交给调用者。','把函数中的 print(number * 2) 改成 return number * 2。'],'返回值可以被保存、继续计算；打印只是显示。','选做挑战')],quizzes:[quiz('fn-q1','只执行 def 定义，函数内部会自动运行吗？',['会','不会，需要调用','取决于名字长短'],1,'定义是准备好操作，调用才会执行。'),quiz('fn-q2','想让计算结果被外部变量保存，应使用？',['return','注释','只用 print()'],0,'return 将结果交给调用者。')]
},
{
 id:'files',title:'把结果写进一个文件',short:'文件读写',chapter:'09',track:'python',stage:'做项目',minutes:15,file:'files.py',lead:'写下一条笔记，再读回来，理解文件与变量的区别。',goals:['用 with open() 写入与读取文本','知道浏览器文件区与电脑文件夹的区别'],concept:'open() 打开文件，"w" 表示覆盖写入，"r" 表示读取。with 会在代码块结束时关闭文件。write() 写入文字，read() 读出文字。encoding="utf-8" 让中文按统一方式编码。',analogy:'变量像你暂时记在脑中的事，文件像写在笔记本上的记录。这里的实验台有自己的虚拟笔记本，不会直接修改你的电脑文件。',code:'# 在浏览器虚拟文件区写入并读取\nwith open("note.txt", "w", encoding="utf-8") as file:\n    file.write("今天学会了文件读写")\n\nwith open("note.txt", "r", encoding="utf-8") as file:\n    text = file.read()\nprint(text)',expected:'今天学会了文件读写',pitfall:'"w" 会覆盖原文件。此处文件只在当前运行环境内保留，刷新或停止重置后可能消失；需要长期保存，请在 VS Code 本地运行，或复制输出保存。',steps:['先写入，再读取。','改掉写入的文字，观察旧内容被替换。','下载 .py 文件，在本地独立文件夹中验证。'],summary:['with：离开代码块时关闭文件','w 覆盖写入；r 读取','utf-8：明确文本编码'],diagram:['程序中的文字','write() 写入文件','read() 读回文字'],terms:['文件','编码','工作目录'],
 tasks:[
 task('file-write','写一句学习记录','把「我能写文件了」写入 practice.txt，然后读取到变量 text 并打印。','# 先写入，再读回\n','# 保存并读取中文\nwith open("practice.txt", "w", encoding="utf-8") as f:\n    f.write("我能写文件了")\nwith open("practice.txt", "r", encoding="utf-8") as f:\n    text = f.read()\nprint(text)','我能写文件了','assert scope.get("text") == "我能写文件了" and open("practice.txt", encoding="utf-8").read() == "我能写文件了" and output.strip() == "我能写文件了", "检查文件内容、读取结果与输出。"',['使用两段 with open()。','第一段模式 w，第二段模式 r。','读取时 text = f.read()。'],'检查实际文件内容，避免只是打印目标文字。'),
 task('file-list','保存待办清单','将「读书」和「练习」两行写入 tasks.txt，再完整读出到 text 并打印。','# 用 \\n 表示换行\n','# 将两行内容保存到文件\nwith open("tasks.txt", "w", encoding="utf-8") as f:\n    f.write("读书\n练习")\nwith open("tasks.txt", "r", encoding="utf-8") as f:\n    text = f.read()\nprint(text)','读书\n练习','assert open("tasks.txt", encoding="utf-8").read() == "读书\\n练习" and output.strip() == "读书\\n练习", "两项任务之间应该有一个真实换行。"',['字符串中的 \\n 表示换行。','写入内容为 "读书\\n练习"。','读回整个文件，再打印。'],'文本文件可以组织多行记录。','综合练习'),
 task('file-overwrite','覆盖写入会留下哪句','用 w 模式先写入「第一句」，再用 w 模式写入「第二句」，读回并打印。','# 第二次写入会发生什么？\n','# w 模式会覆盖旧内容\nwith open("replace.txt", "w", encoding="utf-8") as f:\n    f.write("第一句")\nwith open("replace.txt", "w", encoding="utf-8") as f:\n    f.write("第二句")\nwith open("replace.txt", "r", encoding="utf-8") as f:\n    print(f.read())','第二句','assert output.strip() == "第二句", "第二次 w 模式会替换原有内容。"',['每次 w 都从头写入。','第二句会替换第一句。','最终只留下第二句。'],'需要保留旧内容并继续添加时，可进一步学习 a 追加模式。','选做挑战')],quizzes:[quiz('file-q1','再次用 w 模式打开已有文件，会怎样？',['自动追加','覆盖旧内容','只能读取'],1,'w 代表覆盖写入，操作真实文件前要确认需求。'),quiz('file-q2','网站代码中的 note.txt 默认位于哪里？',['电脑桌面','当前浏览器运行环境的虚拟文件区','云端永久笔记本'],1,'它不等于电脑上的真实文件，也不会自动永久保存。')]
},
{
 id:'errors',title:'读懂报错，把程序救回来',short:'异常与排错',chapter:'10',track:'python',stage:'做项目',minutes:15,file:'errors.py',lead:'先定位原因，再用 try / except 处理可预期的问题。',goals:['从错误名称和行号开始排查','处理数字输入格式不正确的情况'],concept:'运行过程中出现的问题可能触发异常。try 放可能失败的代码，except 指定要处理的异常类型。处理异常不等于忽略所有问题，应给用户明确反馈。',analogy:'像给表单加上检查：有人填了「十二」而不是 12，程序不用直接退出，可以提醒对方输入数字。',code:'# 输入区可以试试 12 和 十二\ntry:\n    age = int(input())\n    print("年龄：", age)\nexcept ValueError:\n    print("请输入整数，例如 12")',stdin:'十二',expected:'请输入整数，例如 12',pitfall:'优先捕获你能处理的具体异常。语法写错、缩进错误，需要先修代码；不要用空的 except 把所有问题藏起来。',steps:['输入「十二」，观察友好提示。','输入 12，确认正常分支也能运行。','读一条报错：最后一行是什么类型，指向哪一行？'],summary:['错误名称：问题类别','行号：定位线索','try / except：处理可预期异常'],diagram:['读取输入并转换','成功：输出结果','ValueError：给出提醒'],terms:['异常','调试','边界'],
 tasks:[
 task('error-value','处理无效数字','读取一个整数，成功则打印它；如果不是整数则输出「请输入整数」。输入区填 abc。','# 给转换加上保护\nnumber = int(input())\nprint(number)','# 只处理数值格式错误\ntry:\n    number = int(input())\n    print(number)\nexcept ValueError:\n    print("请输入整数")','请输入整数','assert output.strip() == "请输入整数", "请在输入区使用 abc，并在 except ValueError 中打印提示。"',['把可能失败的转换放进 try。','捕获 ValueError。','except ValueError: 后缩进输出提示。'],'再用合法数字手动验证正常路径。'),
 task('error-plan','耐心的学习建议','读取 minutes。大于等于 15 输出「开始学习」，否则输出「先复习」；无效数字输出「请输入整数」。输入区填 15。','# 输入转换、判断与错误提示\n','# 让两条正常分支和异常都可理解\ntry:\n    minutes = int(input())\n    if minutes >= 15:\n        print("开始学习")\n    else:\n        print("先复习")\nexcept ValueError:\n    print("请输入整数")','开始学习','assert output.strip() in ["开始学习","先复习","请输入整数"], "应出现对应的一条提示；请分别用 15、5、abc 自测三条路径。"',['先处理输入转换。','把 if / else 放在 try 内。','except 与 try 对齐。'],'当前检查只确认输出形式；请主动使用三组输入验证所有路径。','综合练习'),
 task('error-name','修复名字不一致','修复示例的 NameError，让程序输出 3。','# 大小写需要一致\ndays = 3\nprint(Days)','# 使用同一个名字\ndays = 3\nprint(days)','3','assert scope.get("days") == 3 and output.strip() == "3", "检查 print() 中变量名的大小写。"',['Days 与 days 不同。','检查已经定义的变量名。','将 Days 改成 days。'],'这种问题应该修正名字，而不是用 except 隐藏。','选做挑战')],quizzes:[quiz('error-q1','int("abc") 常见的错误是？',['ValueError','NameError','没有错误'],0,'字符串内容不是整数形式。'),quiz('error-q2','看到 NameError，应该优先检查什么？',['重新安装电脑','变量名拼写和是否已经赋值','删除所有代码'],1,'从最接近问题的线索开始排查，一次改一处。')]
},
{
 id:'modules',title:'借用别人已经写好的工具',short:'模块与环境',chapter:'11',track:'python',stage:'做项目',minutes:12,file:'modules.py',lead:'认识 import，先用 Python 自带的模块完成一个小计算。',goals:['导入并使用一个标准库模块','区分导入模块和安装第三方包'],concept:'模块是可以导入的一组 Python 代码。import math 导入数学工具，math.sqrt(9) 计算平方根。标准库随 Python 提供；第三方包通常需要先安装到当前解释器环境。',analogy:'你不需要自己造每一种工具。import 像从工具箱里取出工具；pip 安装则是先把新的工具放进对应工具箱。',code:'# math 是 Python 自带的标准库\nimport math\n\nnumber = 9\nprint(math.sqrt(number))\nprint(math.ceil(2.1))',expected:'3.0\n3',pitfall:'不要把自己的文件命名为 math.py，否则可能挡住原来的模块。安装第三方包时，安装环境要与运行解释器一致。',steps:['先运行标准库例子，不需要安装。','将 number 改为 16，再运行。','到环境救援查看解释器与 venv 的关系。'],summary:['import：导入模块','标准库：Python 自带','第三方包：需要安装到当前环境'],diagram:['当前解释器','import math','调用 math.sqrt()'],terms:['模块','解释器','虚拟环境'],
 tasks:[
 task('module-sqrt','计算平方根','导入 math，将 math.sqrt(25) 保存为 result 并打印。','# 先导入，再使用\n','# 调用标准库\nimport math\nresult = math.sqrt(25)\nprint(result)','5.0','assert scope.get("result") == 5.0 and output.strip() == "5.0", "先导入 math，再保存并打印平方根结果。"',['第一行需要 import math。','sqrt() 是 math 的工具。','result = math.sqrt(25)。'],'模块名说明这个函数来自哪套工具。'),
 task('module-days','安排学习天数','共有 50 分钟内容，每天 15 分钟。用 math.ceil() 对 50 / 15 向上取整，保存到 days 并打印。','# 不足一天也算一天\n','# 计算需要安排的天数\nimport math\ntotal = 50\ndaily = 15\ndays = math.ceil(total / daily)\nprint(days)','4','assert scope.get("days") == 4 and output.strip() == "4", "50 / 15 超过三天，需要向上取整到四天。"',['/ 得到除法结果。','ceil() 取不小于它的最小整数。','days = math.ceil(total / daily)。'],'工具与业务含义相结合：剩余的学习时间也需要安排一天。','综合练习'),
 task('module-trunc','两种取整有什么区别','分别输出 int(2.1) 与 math.ceil(2.1)。','# 比较截断和向上取整\n','# 相同输入，不同规则\nimport math\nprint(int(2.1))\nprint(math.ceil(2.1))','2\n3','assert output.strip() == "2\\n3", "int(2.1) 为 2，ceil(2.1) 为 3。"',['int() 是向零截断。','ceil() 是向上取整。','结果依次为 2、3。'],'根据需求选函数，不要仅凭名字猜测。','选做挑战')],quizzes:[quiz('module-q1','使用 math 之前需要 pip 安装吗？',['需要','不需要，它属于标准库','必须先学 Java'],1,'标准库随 Python 提供，直接导入即可。'),quiz('module-q2','包安装成功却仍找不到，先检查什么？',['安装与运行是否使用同一个解释器','屏幕分辨率','变量名字的长度'],0,'多环境时，包可能装进了另一个解释器的环境。')]
},
{
 id:'project',title:'做出你的第一个待办清单',short:'实战：待办清单',chapter:'12',track:'python',stage:'项目实战',minutes:25,file:'todo.py',lead:'把变量、列表、函数和输入组合起来，完成一个能添加、查看任务的小项目。',goals:['运行并解释完整项目的数据流','独立增加一个小功能并验证'],concept:'先让核心功能工作：读取任务数量，逐条添加到列表，再按编号展示。项目由「数据」「操作」「交互」三部分组成。函数处理操作，列表保存数据，input() 和 print() 与用户交互。',analogy:'把之前学过的积木拼在一起：列表是收纳盒，函数是操作工具，输入输出是你与工具沟通的窗口。',
 code:'# 第一版待办清单：运行期间保留数据\ndef add_task(tasks, title):\n    tasks.append(title)\n\ndef show_tasks(tasks):\n    for index in range(len(tasks)):\n        print(index + 1, tasks[index])\n\ntasks = []\ntry:\n    count = int(input("要添加几个任务？"))\n    if count < 0 or count > 20:\n        print("请输入 0 到 20 之间的数量")\n    else:\n        for index in range(count):\n            title = input("任务名称：")\n            add_task(tasks, title)\n        print("\n我的待办清单")\n        show_tasks(tasks)\nexcept ValueError:\n    print("数量需要填写整数")',stdin:'2\n读一个例子\n完成一道练习',expected:'要添加几个任务？任务名称：任务名称：\n我的待办清单\n1 读一个例子\n2 完成一道练习',
 pitfall:'len(tasks) 得到任务数量，or 表示任一条件成立。这两种写法在这里首次出现。当前版本只在本次程序运行期间保留 tasks，长期保存可以结合第 9 课文件读写扩展。',steps:['先直接运行完整项目，认识最终效果。','读 add_task() 与 show_tasks()，找到每个函数的职责。','改变输入，添加三条你自己的任务。','依次用 0、2、abc 测试空清单、正常流程和错误输入。'],summary:['列表 tasks：保存任务数据','两个函数：添加与展示','输入 → 校验 → 更新数据 → 展示结果'],diagram:['输入任务','add_task() 更新列表','show_tasks() 展示'],terms:['函数','列表','异常'],
 tasks:[
 task('project-add','实现添加任务','完成 add_task(tasks, title)，让它把 title 加入传入列表。创建 tasks，添加「读书」后打印列表。','# 完成这个小函数\ndef add_task(tasks, title):\n    pass\n\ntasks = []\nadd_task(tasks, "读书")\nprint(tasks)','# pass 是占位符，替换为真正动作\ndef add_task(tasks, title):\n    tasks.append(title)\n\ntasks = []\nadd_task(tasks, "读书")\nprint(tasks)',"['读书']",'assert callable(scope.get("add_task")), "请定义 add_task 函数。"\nsample = []\nscope["add_task"](sample, "测试")\nassert sample == ["测试"] and scope.get("tasks") == ["读书"], "函数应修改传入的列表，添加传入的标题。"',['pass 是临时占位符。','对传入的 tasks 调用 append()。','使用 tasks.append(title)。'],'操作传入的数据，函数才能复用。'),
 task('project-show','给清单加上编号','定义 show_tasks(tasks)，从 1 开始逐行输出编号与任务。调用 show_tasks(["读书", "练习"])。','# 完成清单展示\ndef show_tasks(tasks):\n    pass\n\nshow_tasks(["读书", "练习"])','# 索引从 0 开始，展示编号从 1 开始\ndef show_tasks(tasks):\n    for index in range(len(tasks)):\n        print(index + 1, tasks[index])\n\nshow_tasks(["读书", "练习"])','1 读书\n2 练习','assert callable(scope.get("show_tasks")) and output.strip() == "1 读书\\n2 练习", "检查编号从 1 开始，索引仍从 0 开始。"',['len(tasks) 给出列表长度。','range(len(tasks)) 提供索引。','打印 index + 1 和 tasks[index]。'],'展示编号与内部索引可以不同。完成后请用三项列表自测。','综合练习'),
 task('project-empty','照顾空清单','扩展 show_tasks(tasks)：空列表输出「还没有任务」，否则按编号输出。调用 show_tasks([])。','# 为空清单提供提示\ndef show_tasks(tasks):\n    for index in range(len(tasks)):\n        print(index + 1, tasks[index])\n\nshow_tasks([])','# 长度为 0 就是空列表\ndef show_tasks(tasks):\n    if len(tasks) == 0:\n        print("还没有任务")\n    else:\n        for index in range(len(tasks)):\n            print(index + 1, tasks[index])\n\nshow_tasks([])','还没有任务','assert output.strip() == "还没有任务", "空列表应有明确提示；再用有任务的列表自测。"',['先判断 len(tasks) == 0。','原来的循环放到 else 内。','注意循环内部会比 else 再多一层缩进。'],'空数据也是正常使用场景，好的程序会解释当前状态。','选做挑战')],
 quizzes:[quiz('project-q1','这个项目中，哪部分保存任务？',['tasks 列表','print()','注释'],0,'列表负责保存数据，函数负责操作。'),quiz('project-q2','准备学习 Java 前，更有意义的检查是？',['只看完全部答案','能自己修改一个功能，并说明如何验证','背下所有关键字'],1,'迁移到另一门语言前，先让基本思路稳定下来。')]
},
{
 id:'java-first',title:'在 Java 中，再说一次你好',short:'Java 第一个程序',chapter:'13',track:'java',stage:'Java 起步',minutes:15,file:'Main.java',lead:'先运行一个完整程序，逐步认识 Java 的入口结构。',goals:['在 VS Code 运行 Main.java','知道本章只需修改 main 内的输出语句'],concept:'本例使用传统 Java 程序结构。class 定义类，main 是程序的入口。System.out.println() 输出一行内容。先保留外层结构，逐步理解，不必一次背下全部写法。',analogy:'外层结构像舞台和入口，main 内的语句才是这次上台表演的内容。我们先学会改台词。',code:'public class Main {\n    public static void main(String[] args) {\n        // 输出第一句问候\n        System.out.println("你好，Java！");\n    }\n}',expected:'你好，Java！',pitfall:'保存为 Main.java，与公开类名一致。语句末尾有分号。第一版提供本地运行指南，右侧不会伪装成在线 Java 执行器。',steps:['先打开环境救援，完成 JDK 与 Java 扩展配置。','复制完整程序，保存到 Main.java。','点击 main 上方的 Run，观察终端。','修改文字并重新运行。'],summary:['Main.java：与公开类名一致','main：本例程序入口','System.out.println()：打印一行'],diagram:['Main.java 源文件','JDK 编译与运行','终端显示输出'],terms:['JDK','编译','终端'],compare:[['输出','print("你好")','System.out.println("你好");'],['注释','# 注释','// 注释'],['代码块','缩进','大括号 { }']],tasks:[
 task('java-hello','修改问候','输出「我开始学 Java 了」。','','public class Main {\n    public static void main(String[] args) {\n        // 修改输出文字\n        System.out.println("我开始学 Java 了");\n    }\n}','我开始学 Java 了','',['只修改字符串。','保留分号和括号。','修改 println() 里的文字。'],'在 VS Code 本地运行，对照实际输出。'),
 task('java-two','两行学习名片','依次输出「我是小林」与「今天学习 Java」。','','public class Main {\n    public static void main(String[] args) {\n        // 两条语句依次执行\n        System.out.println("我是小林");\n        System.out.println("今天学习 Java");\n    }\n}','我是小林\n今天学习 Java','',['需要两条语句。','每条 println() 默认换行。','把两条语句都放在 main 内。'],'用两个输出语句组织结果。','综合练习'),
 task('java-fix','故意少写一个分号','在本地删掉一行末尾分号，阅读错误后补回。','','public class Main {\n    public static void main(String[] args) {\n        // 分号标记语句结束\n        System.out.println("修好了");\n    }\n}','修好了','',['观察错误中的 expected。','检查报错行及上一行。','在输出语句末尾补上 ;。'],'错误信息是定位线索，先修复最靠前的问题。','选做挑战')],quizzes:[quiz('java-q1','本例公开类叫 Main，文件应叫什么？',['main.py','Main.java','任意名字.txt'],1,'本例文件名要与公开类名一致。'),quiz('java-q2','本例从哪里开始执行主要语句？',['main 方法内部','注释内部','文件名中'],0,'main 是这里采用的程序入口。')]
},
{
 id:'java-types',title:'先告诉 Java，要存什么数据',short:'Java 变量与类型',chapter:'14',track:'java',stage:'Java 起步',minutes:15,file:'Main.java',lead:'用熟悉的学习档案，理解 Java 的显式类型声明。',goals:['声明 int、double、String、boolean 变量','对照 Python 找出三个主要差异'],concept:'本章使用显式声明：类型、变量名、初始值。int 保存整数，double 保存浮点数，String 保存字符串，boolean 保存真假。重新赋值时，新值必须与变量类型兼容。',analogy:'像给收纳格先贴上「整数」标签。之后不能随意把一段文字塞进这个格子。',code:'public class Main {\n    public static void main(String[] args) {\n        // 声明不同类型的变量\n        String name = "小林";\n        int days = 7;\n        double hours = 1.5;\n        boolean ready = true;\n        System.out.println(name);\n        System.out.println(days + " " + hours + " " + ready);\n    }\n}',expected:'小林\n7 1.5 true',pitfall:'String 大写，true 小写。数字与字符串拼接时，+ 会连接文字。本章先用四种常见类型，char、数值范围与更复杂转换以后再展开。',steps:['找到四种类型及它们的值。','对照 Python 的同一份档案。','把 days 改成 10，重新运行。'],summary:['声明：类型、名字、初始值','新值要与声明类型兼容','String 大写，true / false 小写'],diagram:['int days = 7','days 保存整数 7','days = 10 更新值'],terms:['类型','编译','布尔值'],compare:[['整数','days = 7','int days = 7;'],['文字','name = "小林"','String name = "小林";'],['真假','ready = True','boolean ready = true;']],tasks:[
 task('java-int','声明一个整数','声明 level = 2，类型为 int，并打印。','','public class Main {\n    public static void main(String[] args) {\n        // 保存等级\n        int level = 2;\n        System.out.println(level);\n    }\n}','2','',['类型写在名字前。','语句末尾需要分号。','int level = 2;。'],'先声明，再使用。'),
 task('java-card','Java 学习名片','创建 String name = "小林" 和 int days = 7，输出「小林 7」。','','public class Main {\n    public static void main(String[] args) {\n        // 拼接档案信息\n        String name = "小林";\n        int days = 7;\n        System.out.println(name + " " + days);\n    }\n}','小林 7','',['两个变量需要不同类型。','中间加一个空格字符串。','name + " " + days。'],'变量声明与字符串拼接结合起来。','综合练习'),
 task('java-copy','赋值以后会联动吗','声明 a = 3，再把 a 赋给 b；改 a 为 4，打印 a 与 b。','','public class Main {\n    public static void main(String[] args) {\n        // int 赋值复制当前值\n        int a = 3;\n        int b = a;\n        a = 4;\n        System.out.println(a + " " + b);\n    }\n}','4 3','',['int 是基本类型。','b 保存赋值时的 3。','后续修改 a 不改变 b。'],'此例讲基本类型值的复制，不直接套用到对象共享上。','选做挑战')],quizzes:[quiz('java-type-q1','哪种声明正确？',['boolean ready = True;','boolean ready = true;','bool ready = true;'],1,'Java 使用 boolean 与小写 true。'),quiz('java-type-q2','int days = 7 后，能直接赋值 days = "七" 吗？',['可以','不可以，类型不兼容','只有晚上可以'],1,'字符串不能直接赋给 int 变量。')]
},
{
 id:'java-method',title:'把 Python 函数迁移成 Java 方法',short:'Java 方法与小项目',chapter:'15',track:'java',stage:'Java 起步',minutes:18,file:'Main.java',lead:'用计算学习时长的小程序，认识参数与返回类型。',goals:['识别方法参数和返回类型','调用同一个方法处理不同数据'],concept:'Java 方法同样可以接收参数并返回结果。本例的 static int total(int minutes, int days) 表示：接收两个整数，返回一个整数。static 让本例可以直接从 main 调用；类和对象在后续路线学习。',analogy:'还是那台熟悉的小机器，只是 Java 要你把进料与出料的种类提前标出来。',code:'public class Main {\n    // 接收两个整数，返回一个整数\n    static int total(int minutes, int days) {\n        return minutes * days;\n    }\n    public static void main(String[] args) {\n        System.out.println(total(15, 5));\n        System.out.println(total(20, 3));\n    }\n}',expected:'75\n60',pitfall:'返回类型为 int 的本例方法，需要返回整数。方法定义放在类内部，与 main 并列，不要塞进 main 里面。',steps:['比较参数声明与 Python 的差别。','在本地运行两次调用。','独立改成计算总题数的小工具。'],summary:['方法：命名并复用操作','参数类型：明确输入','返回类型与 return：明确输出'],diagram:['两个 int 参数','total() 内计算','返回 int 结果'],terms:['函数','参数','返回值'],compare:[['定义','def total(minutes, days):','static int total(int minutes, int days)'],['返回','return minutes * days','return minutes * days;'],['代码块','缩进','大括号']],tasks:[
 task('java-double','整数翻倍','定义 static int doubleValue(int n)，返回两倍。调用参数为 4。','','public class Main {\n    // 返回参数的两倍\n    static int doubleValue(int n) {\n        return n * 2;\n    }\n    public static void main(String[] args) {\n        System.out.println(doubleValue(4));\n    }\n}','8','',['返回类型是 int。','使用传入的 n 计算。','return n * 2;。'],'方法处理参数，不能把结果写死。'),
 task('java-plan','迷你学习计划计算器','定义 total 方法；在 main 中保存 minutes = 20、days = 5，输出总时长 100。','','public class Main {\n    // 计算学习计划总分钟数\n    static int total(int minutes, int days) {\n        return minutes * days;\n    }\n    public static void main(String[] args) {\n        int minutes = 20;\n        int days = 5;\n        System.out.println(total(minutes, days));\n    }\n}','100','',['先定义，再在 main 调用。','局部变量作为参数传入。','System.out.println(total(minutes, days));。'],'组合变量、方法和输出，完成一个可修改的计算工具。','综合练习'),
 task('java-repeat','改变数据验证方法','调用 total(0, 5) 和 total(10, 3)，观察边界与普通数据。','','public class Main {\n    // 同一方法验证不同输入\n    static int total(int minutes, int days) {\n        return minutes * days;\n    }\n    public static void main(String[] args) {\n        System.out.println(total(0, 5));\n        System.out.println(total(10, 3));\n    }\n}','0\n30','',['零也是合法的整数。','分别打印两次调用。','输出为 0 和 30。'],'多组数据验证比只看一组结果更可靠。','选做挑战')],quizzes:[quiz('java-method-q1','static int total(...) 中的 int 表示什么？',['方法名','返回结果的类型','执行次数'],1,'方法声明中的返回类型说明它会交回什么数据。'),quiz('java-method-q2','本例 total 方法定义放在哪里？',['Main 类中，与 main 并列','main 的语句里面','引号里面'],0,'方法定义属于类，不写在另一个方法内部。')]
}
];
// 代码中的换行转义属于字符串本身，不应成为源码中的断行。
lessons.find(l=>l.id==='files').tasks[1].answer = lessons.find(l=>l.id==='files').tasks[1].answer.replace('f.write("读书\n练习")','f.write("读书\\n练习")');
lessons.find(l=>l.id==='project').code = lessons.find(l=>l.id==='project').code.replace('print("\n我的待办清单")','print("\\n我的待办清单")');
export const glossary={
 '字符串':'用于表示文字的数据。即使内容看起来是数字，只要写在引号里，通常就是字符串。',
 '注释':'写给人看的代码说明。Python 使用 #，Java 常用 //；注释不会作为程序语句执行。',
 '输出':'程序展示给你的结果。print() 是 Python 常用的输出函数。',
 '输入':'从用户或其他来源读取的数据。在本网站，先把要输入的内容按行填入输入区。',
 '变量':'程序用来关联数据的名字。Python 的名字可以重新关联对象；Java 本章变量有确定类型。',
 '赋值':'先计算右边，再将得到的值赋给左边的名字或变量。它不等于数学中的相等判断。',
 '对象':'Python 中数据以对象的形式存在。先理解为具有某种类型和值的数据，细节后续学习。',
 '类型':'数据的类别，例如整数、字符串。类型会影响它可以执行哪些操作。',
 '布尔值':'只有真与假两种值。Python 写 True / False，Java 写 true / false。',
 '解释器':'真正执行 Python 代码的程序。VS Code 是编辑器，需要选择相应解释器来运行代码。',
 '条件':'结果为真或假的判断，决定程序接下来走哪条分支。',
 '缩进':'一行开头的空白。Python 用它组织代码块，建议每层 4 个空格。',
 '边界':'规则切换处的特殊值，例如及格条件 >= 60 中的 60。测试边界能发现很多逻辑错误。',
 '循环':'重复执行一段代码。for 通常依次处理一组数据，while 根据条件重复。',
 '列表':'用方括号表示的有顺序、可修改的数据集合。Python 索引从 0 开始。',
 '索引':'数据在序列中的位置编号。Python 列表第一项的索引为 0。',
 '字典':'通过键找到对应值的数据结构，例如 {"name": "小林"}。',
 '函数':'有名字的一组操作，可以接收参数，并通过 return 交回结果。',
 '参数':'调用函数或方法时交给它的数据，例如 total(15, 5) 中的 15 和 5。',
 '返回值':'函数用 return 交回给调用者的结果，与直接在屏幕上打印不同。',
 '文件':'按名字保存的数据。本网站 Python 沙盒使用虚拟文件区，本地程序使用电脑文件系统。',
 '编码':'文字和字节之间的转换规则。保存中文文本时通常明确使用 UTF-8。',
 '工作目录':'程序当前所在的目录。相对路径会根据它寻找文件，不一定等于你正在查看的文件位置。',
 '异常':'程序运行时出现、需要处理或修复的问题。先看异常名称、说明和相关行号。',
 '调试':'通过断点、变量观察、输出和小范围验证，找出程序为什么没有按预期工作。',
 '模块':'可以导入并复用的一组代码。标准库自带，第三方模块通常需要安装。',
 '虚拟环境':'为一个 Python 项目准备的独立包环境，帮助不同项目使用各自的依赖。',
 'JDK':'Java 开发工具包，包含编译、运行 Java 程序所需的工具。',
 '编译':'把源代码转换为另一种可执行形式的过程。Java 的编译错误通常在程序运行前发现。',
 '终端':'输入命令并查看结果的窗口。它不是代码文件编辑区。'
};
export const future=[['Python 加深','元组、集合、while、文件版待办清单、生成器与装饰器'],['Java 后续','条件与循环、数组、面向对象、集合、异常、学生管理系统'],['工具进阶','Git 分支协作、项目调试、性能分析']];
lessons.push(...dataLessons);
Object.assign(glossary,dataGlossary);
