export const guides=[
{id:'python',tag:'开始前 · 约 10 分钟',title:'让 Python 在电脑上运行',html:`<ol><li>从 <a href="https://www.python.org/downloads/" target="_blank" rel="noopener">Python 官网</a>安装 Python。</li><li>安装 <a href="https://code.visualstudio.com/download" target="_blank" rel="noopener">VS Code</a>，在扩展页搜索 Microsoft 的 Python 扩展。</li><li>用「文件 → 打开文件夹」打开 <code>D:\\codex\\python-practice</code>，没有就先创建。</li><li>创建 <code>hello.py</code>，输入下方两行代码并保存。</li><li>打开命令面板，执行 <code>Python: Select Interpreter</code>，选择已安装的 Python。</li><li>点击「Run Python File」，在终端确认出现「你好，Python！」。</li></ol><div class="code-head">写进 hello.py 的 Python 代码</div><pre># 输出第一句话\nprint("你好，Python！")</pre><details><summary>如果没有运行成功</summary><p>安装后新开终端或重启 VS Code。终端输入 <code>py --version</code> 检查 Python 是否可用。找不到命令时回到安装与路径检查，不需要反复修改程序。</p></details>`},
{id:'vscode',tag:'工具按需学习',title:'VS Code，只先学这几件事',html:`<ol><li>打开文件夹，而不只是单个文件。</li><li>扩展里安装「Chinese (Simplified) Language Pack」，用 <code>Configure Display Language</code> 切换中文。</li><li>Python 扩展负责语言支持；确认 Python Debugger 可用。</li><li>Java 使用 Extension Pack for Java；Code Runner 可选，入门先用语言扩展自带的运行入口。</li><li>分清编辑区、终端和输出面板。需要 input() 的程序在终端交互。</li></ol><table class="compare"><tr><th>操作</th><th>Windows 默认快捷键</th></tr><tr><td>保存</td><td>Ctrl + S</td></tr><tr><td>命令面板</td><td>Ctrl + Shift + P</td></tr><tr><td>快速打开文件</td><td>Ctrl + P</td></tr><tr><td>全局搜索</td><td>Ctrl + Shift + F</td></tr><tr><td>开始调试</td><td>F5</td></tr><tr><td>单步跳过 / 进入</td><td>F10 / F11</td></tr></table><p class="support-note">键位可修改；笔记本可能需要配合 Fn。<a href="https://code.visualstudio.com/docs/python/python-tutorial" target="_blank" rel="noopener">官方入门教程</a></p>`},
{id:'terminal',tag:'别把命令当代码',title:'终端、路径与文件',html:`<p>终端是输入命令的窗口。先确认当前目录，再运行文件。文件路径有空格时用英文引号包起来。</p><div class="code-head">在 PowerShell 终端输入</div><pre># 查看当前位置\nGet-Location\n# 查看当前目录里的文件\nGet-ChildItem\n# 切换到已创建的练习文件夹\nSet-Location "D:\\codex\\python-practice"\n# 运行保存好的文件\npy hello.py</pre><p>预期：前三步显示位置或文件列表；最后一步显示程序输出。看到 <code>&gt;&gt;&gt;</code> 时，你在 Python 交互环境内，先用 <code>exit()</code> 返回终端。</p>`},
{id:'venv',tag:'用到第三方包时再学',title:'解释器、pip 与虚拟环境',html:`<p>VS Code 是工作台，解释器执行代码，pip 给指定解释器安装包。虚拟环境给项目准备独立的工具箱。</p><div class="code-head">在项目文件夹的 PowerShell 终端输入</div><pre># 创建项目虚拟环境\npy -m venv .venv\n# 检查这个环境对应的 pip\n.\\.venv\\Scripts\\python.exe -m pip --version\n# 使用该环境运行程序，无需先激活\n.\\.venv\\Scripts\\python.exe hello.py</pre><p>预期：生成 .venv 文件夹；pip 路径包含该项目的 .venv；程序正常输出。在 VS Code 选择同一个 .venv 解释器。</p><details><summary>如何给当前项目安装第三方包？</summary><p>需要第三方包时，用同一解释器执行 <code>.\\.venv\\Scripts\\python.exe -m pip install 包名</code>，把「包名」替换成真实名称。Python 入门课程主要使用标准库；数据分析路线需要 NumPy、Pandas、Matplotlib 等扩展包，详见下方数据分析环境。</p></details><details><summary>提示无法运行激活脚本？</summary><p>直接调用虚拟环境里的 python.exe 即可，不必为了入门练习修改系统脚本执行策略。</p></details><p class="support-note"><a href="https://docs.python.org/3/library/venv.html" target="_blank" rel="noopener">Python venv 官方说明</a></p>`},
{id:'java',tag:'完成 Python 项目后再来',title:'Java 本地运行步骤',html:`<ol><li>按 <a href="https://code.visualstudio.com/docs/java/java-tutorial" target="_blank" rel="noopener">VS Code Java 官方教程</a>安装兼容的 JDK 与 Extension Pack for Java。</li><li>新开终端，分别运行 <code>java -version</code> 与 <code>javac -version</code>，应看到预期 JDK 的版本。</li><li>在独立文件夹创建 <code>Main.java</code>，复制 Java 课程完整示例。</li><li>保存后，点击 main 上方的 Run 或 Debug；也可以按下方命令编译运行。</li></ol><div class="code-head">在 Main.java 所在文件夹的终端输入</div><pre># 编译成功时通常没有额外输出\njavac -encoding UTF-8 Main.java\n# 运行已编译的类\njava Main</pre><p>预期输出与课程示例一致。若 java、javac 版本或路径不一致，检查 PATH；JAVA_HOME 指向 JDK 根目录，不是 bin 文件夹。修改后新开终端。</p><a class="button" href="#learn/java-first">打开 Java 第一课</a>`},
{id:'debug',tag:'知道错在哪，比重写更有用',title:'第一次使用断点',html:`<ol><li>打开「变量与赋值」示例，在本地保存。</li><li>在 <code>days = 4</code> 这一行的行号左边点击，出现红点。</li><li>按 F5，选择对应语言调试配置。</li><li>暂停时当前行通常还没执行，先查看 days 是否为 3。</li><li>按 F10 执行这一行，再看 days 是否变为 4。</li><li>按 Shift + F5 停止调试。</li></ol><p>单步跳过是执行当前语句；单步进入用于进入可调试的函数调用。先练习观察一两个变量就足够了。</p><p class="support-note"><a href="https://code.visualstudio.com/docs/java/java-debugging" target="_blank" rel="noopener">Java 调试指南</a></p>`},
{id:'errors',tag:'常见报错翻译',title:'看到报错，先别重装',html:[['NameError / cannot find symbol','找不到名字。检查是否定义、拼写和大小写。'],['SyntaxError / ; expected','写法不符合规则。检查报错行及上一行的英文括号、引号、冒号或分号。'],['ValueError / NumberFormatException','输入不能转成需要的数字格式。整数题不要填「十二」或 1.5。'],['ModuleNotFoundError','模块不在当前解释器环境中。确认安装和运行使用同一个 Python。'],['中文乱码','先确认源文件保存为 UTF-8，再检查终端编码与字体。Java 编译可显式指定 -encoding UTF-8。'],['找不到文件 / 路径错误','确认保存了文件、名字无误、终端目录正确；有空格的路径加引号。'],['网站 Python 加载失败','首次运行需联网加载。可以重试或下载代码，在 VS Code 继续；课程阅读和笔记不依赖执行环境。']].map(([t,p])=>`<details><summary>${t}</summary><p>${p}</p></details>`).join('')},
{id:'git',tag:'做完小项目后',title:'给代码留一份变化记录',html:`<p>Git 记录代码的修改历史。先在项目副本中练习：查看差异、暂存、提交。暂存是选择这次要记录的修改，提交是给它留一个说明。</p><ol><li>安装 <a href="https://git-scm.com/downloads" target="_blank" rel="noopener">Git</a> 并重启 VS Code。</li><li>打开源代码管理，初始化当前项目仓库。</li><li>修改一行，点击文件查看前后差异。</li><li>确认没有密码、隐私文件或 .venv，再暂存所需文件。</li><li>填写说明，如「增加空清单提示」，完成提交。</li></ol><p>预期：修改出现在提交历史中。若提示身份未配置，按提示设置自己的提交姓名与邮箱。Git 记录历史不等于已经上传云端。</p>`}
];
