import {lessons,glossary,future} from './curriculum.js';
import {guides} from './guides.js';
import {scienceGuide} from './data-guides.js';
guides.push(scienceGuide);
const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='code-first-learning-v1'+(new URLSearchParams(location.search).has('qa')?'-qa':''),blank=()=>({version:1,last:'hello',visited:{},goals:{},notes:{},drafts:{},inputs:{},ratings:{},answers:{},tasks:{},mistakes:{},help:{},seconds:0,theme:'system'});
let state=blank(),storageError=false,tab='read',route='learn',lesson=lessons[0],activeTask=null,activeCard=null,worker=null,job=null,jobTimer;
let hints={},seenAnswers={},answerOpen={},outputs={},reviewFilter='pending',lastActivity=Date.now(),toastTimer,pendingImport=null;
function validate(raw){
 if(!raw||raw.version!==1||Array.isArray(raw))throw Error('不是有效的码上起步备份。');const out=blank();
 for(const key of ['visited','goals','notes','drafts','inputs','ratings','answers','tasks','mistakes']){if(!raw[key]||typeof raw[key]!=='object'||Array.isArray(raw[key])||Object.keys(raw[key]).length>5000)throw Error('备份结构无效：'+key);out[key]=Object.fromEntries(Object.entries(raw[key]).filter(([k])=>!['__proto__','constructor','prototype'].includes(k)));}
 for(const key of ['notes','drafts','inputs'])for(const v of Object.values(out[key]))if(typeof v!=='string'||v.length>200000)throw Error('备份文本格式无效。');
 for(const v of Object.values(out.goals))if(!Array.isArray(v)||v.some(x=>typeof x!=='boolean'))throw Error('目标格式无效。');
 for(const v of Object.values(out.ratings))if(!['practiced','independent'].includes(v))throw Error('状态格式无效。');
 for(const v of Object.values(out.answers))if(!v||typeof v.first!=='boolean'||typeof v.latest!=='boolean'||!Number.isInteger(v.selected))throw Error('测验格式无效。');
 for(const v of Object.values(out.tasks))if(!v||typeof v.passed!=='boolean'||typeof v.first!=='boolean')throw Error('练习格式无效。');
 for(const v of Object.values(out.mistakes))if(!v||!['quiz','code'].includes(v.type)||!lessons.some(l=>l.id===v.lessonId)||typeof v.resolved!=='boolean'||typeof v.title!=='string'||typeof v.original!=='string')throw Error('错题格式无效。');
 if(raw.help&&typeof raw.help==='object'&&!Array.isArray(raw.help)){for(const [id,v] of Object.entries(raw.help)){if(lessons.some(l=>l.tasks.some(t=>t.id===id))&&v&&Number.isInteger(v.hints)&&v.hints>=0&&v.hints<=3&&typeof v.answer==='boolean')out.help[id]=v;}}
 out.last=lessons.some(l=>l.id===raw.last)?raw.last:'hello';out.seconds=Number.isFinite(raw.seconds)?Math.max(0,Math.min(raw.seconds,1e9)):0;out.theme=['light','dark','system'].includes(raw.theme)?raw.theme:'system';return out;
}
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw)state=validate(raw);}catch{storageError=true;}
for(const [id,v] of Object.entries(state.help)){hints[id]=v.hints;seenAnswers[id]=v.answer;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageError=false;return true;}catch{storageError=true;toast('浏览器无法保存，请导出备份。');return false;}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function icon(n){const paths={learn:'M4 4h16v16H4z M8 4v16 M8 9h12',path:'M5 5h5v5H5z M14 14h5v5h-5z M10 7h6v7',mistakes:'M5 3h14v18H5z M8 8h8 M8 12h5 M8 16h7',notes:'M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h4',help:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4 M12 16v1',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',check:'M5 12l4 4L19 6',play:'M8 5l11 7-11 7z',code:'M8 6l-6 6 6 6 M16 6l6 6-6 6'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.learn}"/></svg>`;}
const tracks={python:'Python 入门',java:'Java 起步',numpy:'NumPy 数组',pandas:'Pandas 表格',matplotlib:'Matplotlib 画图',analysis:'数据综合实战'};
const labels={learn:'学习空间',path:'学习路线',mistakes:'错题本',notes:'我的笔记',help:'环境救援'};
const status=l=>state.ratings[l.id]==='independent'?'能独立完成':state.ratings[l.id]==='practiced'?'练习过':state.visited[l.id]?'接触过':'未开始';
const pending=()=>Object.values(state.mistakes).filter(m=>!m.resolved).length;
function percent(first=false){const a=Object.values(state.answers);return a.length?Math.round(100*a.filter(x=>first?x.first:x.latest).length/a.length)+'%':'—';}
function theme(){document.documentElement.classList.toggle('dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));$('#theme-btn').setAttribute('aria-label',document.documentElement.classList.contains('dark')?'切换浅色模式':'切换深色模式');}
function sidebar(){
 $('#track-select').value=lesson.track;
 $('#navigation').innerHTML=Object.entries(labels).map(([id,title])=>`<a href="#${id}${id==='learn'?'/'+state.last:''}" class="${route===id?'active':''}" ${route===id?'aria-current="page"':''}>${icon(id)}${title}${id==='mistakes'&&pending()?`<span class="tag">${pending()}</span>`:''}</a>`).join('');
 $('#lesson-list').innerHTML=lessons.filter(l=>l.track===lesson.track).map(l=>`<a href="#learn/${l.id}" class="lesson-mini ${l.id===lesson.id&&route==='learn'?'current':''} ${state.ratings[l.id]?'done':''}" title="${esc(l.title)} · ${status(l)}"><span class="dot"></span><span>${l.chapter} ${esc(l.short)}</span></a>`).join('');
}
function navigate(){
 const p=location.hash.replace(/^#/,'').split('/');route=Object.hasOwn(labels,p[0])?p[0]:'learn';
 if(route==='learn'){const next=lessons.find(l=>l.id===p[1])||lessons.find(l=>l.id===state.last)||lessons[0];if(next.id!==lesson.id||p[2]){stop(false);activeTask=null;activeCard=null;tab=['read','practice','quiz','notes'].includes(p[2])?p[2]:'read';}lesson=next;state.last=lesson.id;state.visited[lesson.id]=true;save();}
 $('#sidebar').classList.remove('open');render();window.scrollTo({top:0,behavior:'instant'});
}
function heading(title,description,label='ONE SMALL STEP, EVERY DAY'){return `<div class="page-heading"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${description}</p></div><div class="date-chip">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</div></div>`;}
function render(){sidebar();$('#breadcrumb').innerHTML=`${labels[route]} <span>/</span> ${route==='learn'?tracks[lesson.track]:'码上起步'}`;document.title=`${route==='learn'?lesson.title:labels[route]} · 码上起步`;({learn:renderLearn,path:renderPath,mistakes:renderMistakes,notes:renderNotes,help:renderHelp}[route])();}
function renderLearn(){
 const total=lessons.filter(l=>l.track===lesson.track).length,done=lessons.filter(l=>l.track===lesson.track&&state.ratings[l.id]).length,sequence=lessons.filter(l=>['numpy','pandas','matplotlib','analysis'].includes(lesson.track)?['numpy','pandas','matplotlib','analysis'].includes(l.track):l.track===lesson.track),index=sequence.indexOf(lesson);
 $('#main').innerHTML=heading('今天，从一个小任务开始。','不用一次学会所有。理解一点，动手一点，就是进步。')+`<div class="stats-row"><div class="stat"><span class="stat-icon">${icon('path')}</span><div><strong>${done}<span>/ ${total} 个本路线章节</span></strong><small>已练习 · 按自己的节奏前进</small></div></div><div class="stat"><span class="stat-icon">${icon('check')}</span><div><strong>${percent()}</strong><small>最近测验正确率 · 首次 ${percent(true)}</small></div></div><div class="stat"><span class="stat-icon">${icon('clock')}</span><div><strong>${Math.floor(state.seconds/60)}<span>分钟</span></strong><small>累计有效学习时间</small></div></div></div><section class="lesson-banner"><div><div class="banner-meta"><span class="tag">${lesson.track.toUpperCase()} · ${lesson.stage}</span><span>约 ${lesson.minutes} 分钟 · 可分次完成</span></div><h2>${esc(lesson.title)}</h2><p>${esc(lesson.lead)}</p></div><div class="banner-number">${lesson.chapter}</div></section><div class="learning-grid"><section class="panel"><div class="tabs" role="tablist" aria-label="章节内容">${[['read','读懂例子'],['practice','动手练习'],['quiz','小测验'],['notes','本章笔记']].map(([id,title])=>`<button class="tab ${tab===id?'active':''}" role="tab" aria-selected="${tab===id}" aria-controls="lesson-content" id="tab-${id}" data-tab="${id}">${title}</button>`).join('')}</div><div class="lesson-body" id="lesson-content" role="tabpanel" aria-labelledby="tab-${tab}"></div></section><div class="editor-column"><div id="editor-host"></div><section class="panel next-action"><div class="tiny">按自己的节奏前进</div><h3>这一小步，你走到哪里了？</h3><p>可以借助提示，也可以先去下一课。你的学习状态由你确认。</p><div class="rating-options"><button class="button ${state.ratings[lesson.id]==='practiced'?'primary':''}" data-rate="practiced">我练习过了</button><button class="button ${state.ratings[lesson.id]==='independent'?'primary':''}" data-rate="independent">我能独立完成</button></div><div class="progress-bar"><span style="width:${Math.round(done/total*100)}%"></span></div></section><p class="support-note">${lesson.track!=='java'?'Python 在浏览器中实际运行，首次需联网加载。':'Java 练习在 VS Code 中运行并自查。'}<br>遇到问题？<a href="#help">打开环境救援</a> · <button class="text-button" data-action="glossary">查术语</button></p></div></div><div class="lesson-nav">${index>0?`<a href="#learn/${sequence[index-1].id}">上一课 · ${sequence[index-1].short}</a>`:'<span></span>'}<a href="#path">查看学习路线</a>${index<sequence.length-1?`<a href="#learn/${sequence[index+1].id}">下一课 · ${sequence[index+1].short}</a>`:'<a href="#path">回顾这段学习</a>'}</div>`;
 renderBody();renderEditor();$('.lesson-banner > div').insertAdjacentHTML('beforeend','<button class="banner-practice" data-action="jump-editor">去实验台动手</button>');
}
function highlight(text){const re=/(#[^\n]*|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:def|return|for|in|if|else|try|except|with|as|import|True|False|None|pass|or|public|static|class|void|int|double|boolean|String|true|false)\b|\b\d+(?:\.\d+)?\b)/g;let end=0,out='';for(const m of text.matchAll(re)){out+=esc(text.slice(end,m.index));const t=m[0],cls=t.startsWith('#')||t.startsWith('//')?'comment':/^["']/.test(t)?'string':/^\d/.test(t)?'number':'keyword';out+=`<span class="hl-${cls}">${esc(t)}</span>`;end=m.index+t.length;}return out+esc(text.slice(end));}
function renderBody(){
 const body=$('#lesson-content');if(!body)return;$$('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});body.setAttribute('aria-labelledby','tab-'+tab);
 if(tab==='read')body.innerHTML=`<div class="goals"><h3>这个小任务，你会学到</h3>${lesson.goals.map((g,i)=>`<label><input type="checkbox" data-goal="${i}" ${state.goals[lesson.id]?.[i]?'checked':''}>${esc(g)}</label>`).join('')}</div><h2 class="step-title"><span class="step-num">01</span>${lesson.id==='hello'?'让想法有一个看得见的结果':'先读懂它，为什么有用'}</h2><p class="body-copy">${esc(lesson.concept)}</p><div class="analogy"><strong>你可以这样想</strong>${esc(lesson.analogy)}</div><h2 class="step-title"><span class="step-num">02</span>读一段代码，猜一猜结果</h2><div class="code-example"><div class="code-head">${lesson.track==='java'?'JAVA':'PYTHON'} · ${lesson.file}<button class="text-button" data-action="copy-example">复制</button></div><pre>${highlight(lesson.code)}</pre></div><details><summary>展开预期输出 · 先猜，再看</summary><div class="output-example"><span>这是预期结果，不代表已经运行</span><pre>${esc(lesson.expected)}</pre></div></details><div class="pitfall"><strong>小心这个地方</strong><br>${esc(lesson.pitfall)}</div>${knowledgeCards()}<h2 class="step-title"><span class="step-num">03</span>现在轮到你了</h2><ol class="inline-checks">${lesson.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><button class="button primary" data-action="practice">开始动手练习 ${icon('code')}</button><details><summary>看一眼，它是怎么工作的</summary><div class="diagram">${lesson.diagram.map((s,i)=>`${i?'<span aria-hidden="true">›</span>':''}<span class="diagram-box">${esc(s)}</span>`).join('')}</div></details>${lesson.compare?`<details><summary>Python 与 Java，小小对照一下</summary><table class="compare"><thead><tr><th>目的</th><th>Python</th><th>Java</th></tr></thead><tbody>${lesson.compare.map(r=>`<tr>${r.map(t=>`<td>${esc(t)}</td>`).join('')}</tr>`).join('')}</tbody></table></details>`:''}<details><summary>带走这 ${lesson.summary.length} 个知识点</summary><ul class="inline-checks">${lesson.summary.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details><details><summary>报错时，按这个顺序检查</summary><ol class="inline-checks"><li>读错误名称与说明，定位自己的代码行。</li><li>检查英文符号、变量名和缩进。</li><li>确认输入与程序预期一致。</li><li>一次改一个问题，再次运行验证。</li></ol><a class="text-button" href="#help/errors">查看具体报错的处理方法</a></details><div class="support-note">本课术语：${lesson.terms.map(t=>`<button class="term" data-term="${t}" title="${esc(glossary[t]||'')}">${t}</button>`).join(' · ')}</div>${lesson.sources?'<p class="support-note">延伸阅读：'+lesson.sources.map(([title,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)}</a>`).join(' · ')+'</p>':''}`;
 if(tab==='practice')body.innerHTML='<p class="section-kicker">预测 · 修改 · 独立完成 · 排错</p><p class="body-copy" style="margin-bottom:22px">每次只做一题。载入实验台后修改、运行、检查。提示可以一级一级打开。</p>'+lesson.tasks.map(taskCard).join('');
 if(tab==='quiz')body.innerHTML='<p class="section-kicker">随时检查理解，不锁关、不倒计时</p>'+lesson.quizzes.map(quizCard).join('')+'<p class="support-note">首次成绩会保留，重做更新最近成绩。答错进入错题本，答对标为已复习。</p>';
 if(tab==='notes')body.innerHTML=`<h2 style="margin-bottom:10px">留一句话，给下次的自己</h2><p class="body-copy" style="margin-bottom:15px">我理解了什么？哪里还模糊？今天修好了哪个错误？</p><label class="sr-only" for="chapter-note">本章个人笔记</label><textarea id="chapter-note" class="notes-area" placeholder="今天我学会了……\n我容易混淆的是……\n下次想再试一下……">${esc(state.notes[lesson.id]||'')}</textarea><div class="note-status" id="note-status">${storageError?'当前无法保存，请导出备份':'输入后自动保存在当前浏览器'}</div><button class="button" data-action="export-note">导出本课笔记</button><p class="support-note">清理浏览器数据可能删除笔记。请在页脚「备份与恢复」导出全部记录。</p>`;
}
function taskCard(t,i){const r=state.tasks[t.id];return `<article class="practice-card" id="task-${t.id}"><span class="tag">${t.kind}${r?.passed?' · '+({independent:'独立通过',hint:'提示后通过',answer:'参考后通过',self:'本地自查'}[r.mode]||'已通过'):''}</span><h3>${i+1}. ${esc(t.title)}</h3><p>${esc(t.prompt)}</p><div class="practice-actions"><button class="button primary" data-task="${t.id}">${activeTask?.id===t.id?'正在实验台练习':'载入实验台'}</button><button class="button" data-hint="${t.id}">提示 ${hints[t.id]||0}/3</button><button class="text-button" data-answer="${t.id}">${answerOpen[t.id]?'收起答案':'参考答案与解析'}</button></div>${t.hints.slice(0,hints[t.id]||0).map((h,n)=>`<div class="hint">提示 ${n+1}：${esc(h)}</div>`).join('')}${answerOpen[t.id]?`<div class="hint"><strong>参考答案</strong><pre>${esc(t.answer)}</pre><div class="output-example"><span>预期输出</span><pre>${esc(t.expected)}</pre></div><p>${esc(t.explain)}</p><p class="support-note">收起答案，换一组数据再试一次。</p></div>`:''}${r?`<div class="feedback ${r.passed?'correct':''}">${r.passed?'已完成。'+esc(t.explain):'上次还没通过：'+esc(r.message||'对照要求再试一次。')}</div>`:''}</article>`;}
function quizCard(q,i){const a=state.answers[q.id];return `<article class="practice-card"><span class="tag">理解检查 ${i+1}</span><h3>${esc(q.prompt)}</h3><form data-quiz="${q.id}"><div class="quiz-options">${q.options.map((o,n)=>`<label class="quiz-option"><input type="radio" name="${q.id}" value="${n}" ${a?.selected===n?'checked':''}><span>${String.fromCharCode(65+n)}. ${esc(o)}</span></label>`).join('')}</div><button class="button primary" type="submit">${a?'再检查一次':'检查答案'}</button></form>${a?`<div class="feedback ${a.latest?'correct':''}"><strong>${a.latest?'理解正确':'再想一步'}</strong><br>${esc(q.explain)}</div>`:''}</article>`;}
const draftKey=()=>activeTask?`${lesson.id}:${activeTask.id}`:activeCard!==null?`${lesson.id}:example:${activeCard}`:lesson.id;
const starter=()=>activeTask?(activeTask.starter||lesson.code):activeCard!==null?lesson.cards[activeCard].code:lesson.code;
function inputDefault(){return activeTask?({'input-next':'20','input-hours':'15\n5','if-plan':'10','error-value':'abc','error-plan':'15'}[activeTask.id]??lesson.stdin??''):lesson.stdin||'';}
function renderEditor(){
 const key=draftKey(),code=state.drafts[key]??starter(),out=outputs[key];
 $('#editor-host').innerHTML=`<section class="editor-panel"><div class="editor-title"><strong><span class="file-dot"></span>${lesson.file}</strong><div class="editor-tools"><button data-action="copy-code">复制</button><button data-action="reset">重置</button><button data-action="download">下载</button></div></div>${activeCard!==null?`<div class="runtime-help">知识点示例：${esc(lesson.cards[activeCard].title)} <button class="text-button" data-action="exit-example">回到主示例</button></div>`:''}${activeTask?`<div class="runtime-help">正在练习：${esc(activeTask.title)} <button class="text-button" data-action="exit-task">回到示例</button></div>`:''}<div class="editor-wrap"><pre class="code-highlight" aria-hidden="true"><code id="highlighted-code">${highlight(code)}\n</code></pre><textarea id="code-editor" class="code-edit" aria-label="${lesson.track!=='java'?'Python':'Java'} 代码编辑器" spellcheck="false" autocapitalize="off" autocomplete="off" autocorrect="off" wrap="off">${esc(code)}</textarea></div>${lesson.track!=='java'?`<div class="editor-input"><label for="stdin-input">程序输入 · 每个 input() 读取一行</label><textarea id="stdin-input" rows="2" placeholder="无输入的程序可留空">${esc(state.inputs[key]??inputDefault())}</textarea></div><div class="editor-action"><small id="run-status">${job?'正在运行…':'真实 Python · 每次重新创建变量'}</small><div class="run-buttons"><button class="button" data-action="stop" id="stop-btn" ${job?'':'hidden'}>停止</button><button class="button primary" data-action="run" id="run-btn" ${job?'disabled':''}>${icon('play')}${activeTask?'运行并检查':'运行代码'}</button></div></div>`:'<div class="editor-action"><small>Java 在 VS Code 本地运行</small><a class="button primary" href="#help/java">查看运行步骤</a></div>'}<div class="editor-output"><div class="output-title"><span>实际输出</span><button class="text-button" data-action="clear">清空</button></div><pre id="actual-output" class="${out?.error?'error':''}" aria-live="polite">${esc(out?.text??(lesson.track==='java'?'本地运行后，在 VS Code 终端查看结果。':'运行后，你会在这里看到结果。'))}</pre></div><div id="run-feedback">${out?.feedback||''}</div><div id="run-artifacts">${artifacts(out)}</div></section>${activeTask&&lesson.track==='java'?'<div class="panel next-action"><h3>本地自查</h3><p>在 VS Code 运行并对照预期输出，再记录完成。本网站不会把它标为在线判题通过。</p><button class="button" data-action="self-check">已在本地运行并核对</button></div>':''}`;
 $('#code-editor').addEventListener('input',e=>{state.drafts[key]=e.target.value;$('#highlighted-code').innerHTML=highlight(e.target.value)+'\n';syncScroll();save();});$('#code-editor').addEventListener('scroll',syncScroll);
 $('#code-editor').addEventListener('keydown',e=>{if(e.key==='Tab'&&!e.shiftKey){e.preventDefault();const el=e.target;el.setRangeText('    ',el.selectionStart,el.selectionEnd,'end');el.dispatchEvent(new Event('input'));}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run();}});
 $('#stdin-input')?.addEventListener('input',e=>{state.inputs[key]=e.target.value;save();});
}
function syncScroll(){const ed=$('#code-editor'),hi=$('.code-highlight');if(hi&&ed){hi.style.height=ed.clientHeight+'px';hi.scrollTop=ed.scrollTop;hi.scrollLeft=ed.scrollLeft;}}
function runState(text,busy){if($('#run-status'))$('#run-status').textContent=text;if($('#run-btn'))$('#run-btn').disabled=busy;if($('#stop-btn'))$('#stop-btn').hidden=!busy;}
function errorHelp(error){const entries=[['NameError','找不到名字。检查拼写、大小写，并确认使用前已经赋值。'],['IndentationError','缩进不一致。检查冒号后的代码块，统一使用每层 4 个空格。'],['SyntaxError','检查英文引号、括号、冒号，以及报错行的上一行。'],['ValueError','检查数值内容、数组 shape、广播维度或读取参数。不能 reshape 时先核对元素总数。'],['TypeError','数据类型与操作不匹配。检查是否把数字文字直接用于数字计算。'],['IndexError','列表索引越界。第一项是 0，最后一项索引比长度少 1。'],['KeyError','找不到这个键或列名。检查 df.columns、索引标签及大小写。'],['EOFError','输入区的答案不够。每个 input() 需要一行，请补齐。'],['FileNotFoundError','文件没找到。先创建文件，检查名字与工作目录。'],['ModuleNotFoundError','缺少模块或网络加载失败。本站支持 NumPy、Pandas、Matplotlib 和 openpyxl；其他包可在本地安装。'],['ZeroDivisionError','除数是零。检查用于除法的变量。'],['RuntimeError','输出量过大或环境出现问题。减少循环次数与打印内容。']];return entries.find(([n])=>error.includes(n))?.[1]||'先读报错最后一行，再定位你的代码行。一次只改一个问题。';}
function run(){
 if(lesson.track==='java'||job)return;const code=$('#code-editor').value;if(!code.trim()){toast('先写一点代码，再运行。');return;}
 const key=draftKey();state.drafts[key]=code;state.inputs[key]=$('#stdin-input').value;save();const id=Date.now();job={id,key,lessonId:lesson.id,task:activeTask,code};
 runState(worker?'正在执行…':'首次加载 Python，请稍候…',true);$('#actual-output').textContent='正在准备运行…';$('#actual-output').classList.remove('error');$('#run-feedback').innerHTML='';$('#run-artifacts').innerHTML='';
 if(!worker){worker=new Worker(new URL('./science-worker.js',import.meta.url),{type:'module'});worker.onmessage=onWorker;worker.onerror=()=>failRun('Python 环境未能加载。请检查网络后重试，或下载代码在 VS Code 本地运行。');}
 clearTimeout(jobTimer);jobTimer=setTimeout(()=>failRun('环境加载超时。请检查网络后重试；也可以下载代码在 VS Code 本地运行。'),120000);
 worker.postMessage({id,code,stdin:state.inputs[key],test:activeTask?.test||''});
}
function onWorker({data}){
 if(!job||data.id!==job.id)return;
 if(data.status==='loading'){runState(data.message||'正在加载，可以随时停止。',true);return;}
 if(data.status==='running'){clearTimeout(jobTimer);jobTimer=setTimeout(()=>failRun('运行超过 10 秒，已停止。检查是否有无法结束的循环，再修改重试。'),10000);runState('正在执行你的代码…',true);return;}
 if(data.status==='failed'){failRun('运行环境暂时不可用：'+String(data.error||'加载失败')+'。请重试，或下载代码在 VS Code 中运行。');return;}
 clearTimeout(jobTimer);const finished=job;job=null;let feedback='';
 if(data.error)feedback=`<div class="runtime-help"><strong>把报错翻译成人话</strong><br>${esc(errorHelp(data.error))}<br><a href="#help/errors" class="text-button">查看排查步骤</a></div>`;
 if(finished.task){const passed=!data.error&&data.passed===true,message=data.error?errorHelp(data.error):data.testMessage;recordTask(finished,passed,message);feedback+=`<div class="runtime-help"><strong>${passed?'这一题通过了':'再修改一小步'}</strong><br>${esc(passed?finished.task.explain:message||'对照题目检查输出。')}${passed?'<br>再换一组数据验证一下，会更踏实。':''}</div>`;}
 outputs[finished.key]={text:(data.output||'')+(data.error?'\n'+data.error:'')||'程序已执行，没有打印内容。',error:!!data.error,feedback,figures:data.figures||[],files:data.files||[],versions:data.versions||{}};
 if(route==='learn'&&draftKey()===finished.key){$('#actual-output').textContent=outputs[finished.key].text;$('#actual-output').classList.toggle('error',!!data.error);$('#run-feedback').innerHTML=feedback;$('#run-artifacts').innerHTML=artifacts(outputs[finished.key]);runState(data.error?'遇到问题，按提示修改后重试':'执行完成',false);if(tab==='practice')renderBody();}sidebar();
}
function recordTask(f,passed,message){const t=f.task,old=state.tasks[t.id];state.tasks[t.id]={first:old?.first??passed,passed,mode:seenAnswers[t.id]?'answer':hints[t.id]?'hint':'independent',message:message||'',at:Date.now()};if(!passed){const prev=state.mistakes[t.id];state.mistakes[t.id]={...prev,type:'code',lessonId:f.lessonId,title:t.title,original:prev?.original??f.code,lastError:message||'检查题目要求',resolved:false,at:Date.now()};}else if(state.mistakes[t.id])state.mistakes[t.id].resolved=true;save();}
function stop(notify=true){const was=!!job;clearTimeout(jobTimer);if(worker&&was){worker.terminate();worker=null;}job=null;runState('已停止，下次运行将重新准备环境。',false);if(was&&notify){if($('#actual-output'))$('#actual-output').textContent='你已停止本次运行，代码草稿已保留。';toast('已停止，代码草稿已保留。');}}
function failRun(message){const f=job;stop(false);if(!f)return;const feedback=`<div class="runtime-help">${esc(message)}<br><a href="#help" class="text-button">在本地继续练习</a></div>`;outputs[f.key]={text:message,error:true,feedback};if(route==='learn'&&draftKey()===f.key){$('#actual-output').textContent=message;$('#actual-output').classList.add('error');$('#run-feedback').innerHTML=feedback;runState('已停止，可以修改后重试',false);}}
function renderPath(){
 $('#main').innerHTML=heading('路线很清楚，步子可以很小。','Python 基础之后，可以选择数据分析路线或 Java。先完成必学，再按需进入选学。','YOUR LEARNING JOURNEY')+`<section class="panel list-card"><h3>今天只有 15 分钟？</h3><p>继续上次的小任务，完成一个修改就很好。用「接触过 → 练习过 → 能独立完成」记录真实感受。</p><a class="button primary" href="#learn/${state.last}">继续上次学习</a><a class="button" href="#help">先准备开发工具</a></section>${dataRoadmap()}${[['起步','01','先看见结果，再理解数据'],['会交互','02','让程序接收输入、做出判断'],['会组织','03','重复处理数据，复用你的代码'],['做项目','04','保存结果，学会排错与使用工具'],['项目实战','05','组合积木，做出一个完整小程序'],['Java 起步','06','选学：把已经掌握的思路迁移过来']].map(([stage,n,desc])=>`<section class="map-section"><div class="map-header"><span class="track-number">${n}</span><div><h2>${stage==='Java 起步'?'Java 起步 · Python 项目后再学':stage}</h2><p>${desc}</p></div></div><div class="course-grid">${lessons.filter(l=>l.stage===stage).map(l=>`<a class="course-card" href="#learn/${l.id}"><span class="tag">${l.track.toUpperCase()} · ${l.chapter}</span><h3>${esc(l.title)}</h3><p>${esc(l.lead)}</p><small><span>约 ${l.minutes} 分钟</span><span>${status(l)}</span></small></a>`).join('')}</div></section>`).join('')}<section class="panel list-card"><h2>后续学习地图</h2><p class="meta">这些是后续扩展方向，尚未开放。当前已开放 ${lessons.length} 个章节与工具救援。</p>${future.map(([title,desc])=>`<p><strong>${title}</strong> · ${desc}</p>`).join('')}</section>`;
}
function renderMistakes(){const all=Object.entries(state.mistakes),items=all.filter(([,m])=>reviewFilter==='all'||!m.resolved);$('#main').innerHTML=heading('错过一次，就多理解一点。','错题是下一次练习的起点。重做答对后，记录会标为已复习。','LEARN FROM THE LITTLE THINGS')+`<div class="practice-actions" style="margin-bottom:20px"><button class="button ${reviewFilter==='pending'?'primary':''}" data-filter="pending">待复习 ${pending()}</button><button class="button ${reviewFilter==='all'?'primary':''}" data-filter="all">全部记录 ${all.length}</button></div>`+(items.length?items.map(([id,m])=>{const l=lessons.find(l=>l.id===m.lessonId),q=l?.quizzes.find(q=>q.id===id);return `<section class="panel list-card"><div class="meta">${esc(l?.short||'')} · ${m.resolved?'已复习':'待复习'}</div><h2>${esc(m.title)}</h2><details><summary>看看当时卡在哪里</summary><pre>${esc(m.original)}</pre>${m.lastError?`<p>${esc(m.lastError)}</p>`:''}</details>${q?quizCard(q,0):`<a class="button primary" href="#learn/${m.lessonId}/practice" data-review-task="${id}">回到代码题重做</a>`}<a class="text-button" href="#learn/${m.lessonId}">复习相关知识</a></section>`;}).join(''):`<section class="panel empty"><div class="empty-icon">✓</div><h2>${all.length?'这轮错题，已经复习好了。':'还没有错题，也没有压力。'}</h2><p>去做一道小测验，或检查一段练习代码。需要再练的地方会自动收集到这里。</p><a class="button primary" href="#learn/${state.last}/quiz">做一个理解检查</a></section>`);}
function renderNotes(){const notes=Object.entries(state.notes).filter(([id,s])=>s.trim()&&lessons.some(l=>l.id===id));$('#main').innerHTML=heading('把理解，写成自己的话。','每课的笔记自动汇集在这里。点击继续记录，可以回到对应章节。','NOTES TO YOUR FUTURE SELF')+(notes.length?notes.map(([id,n])=>{const l=lessons.find(l=>l.id===id);return `<article class="panel list-card"><div class="meta">${l.track.toUpperCase()} · ${l.chapter}</div><h2>${l.title}</h2><p style="white-space:pre-wrap">${esc(n)}</p><a class="button" href="#learn/${id}/notes">继续记录</a></article>`;}).join(''):`<section class="panel empty"><div class="empty-icon">▧</div><h2>第一句笔记，可以很简单。</h2><p>比如：「变量像名字标签，重新赋值会改变它关联的数据。」用自己的话写下来，就多理解了一点。</p><a class="button primary" href="#learn/${state.last}/notes">写第一条笔记</a></section>`);}
function renderHelp(){$('#main').innerHTML=heading('卡住的时候，先找一个小线索。','以下以 Windows 为例。注意区分终端命令与写进代码文件的内容。','YOUR TOOLKIT & RESCUE GUIDE')+'<div class="guide-grid">'+guides.map(g=>`<section class="panel guide" id="${g.id}"><span class="tag">${g.tag}</span><h2>${g.title}</h2>${g.html}</section>`).join('')+'</div>';const target=location.hash.split('/')[1];if(target)setTimeout(()=>document.getElementById(target)?.scrollIntoView({block:'start'}),0);}
function utility(title,html){$('#utility-title').textContent=title;$('#utility-body').innerHTML=html;if(!$('#utility-dialog').open)$('#utility-dialog').showModal();}
function glossaryDialog(term){if(term)utility(term,`<p>${esc(glossary[term]||'')}</p>`);else utility('术语小词典',Object.entries(glossary).map(([term,text])=>`<details><summary>${term}</summary><p>${esc(text)}</p></details>`).join(''));}
function download(text,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制，可以粘贴使用。');}catch{utility('复制内容',`<p>浏览器暂时不允许自动复制，请选中下方内容复制。</p><textarea class="notes-area" readonly>${esc(text)}</textarea>`);}}
function backup(){utility('学习记录 · 备份与恢复','<p>笔记、草稿、错题和进度保存在当前浏览器，不会自动跨设备同步。清理网站数据前，请导出备份。</p><button class="button primary" data-action="export-all">导出全部学习记录</button><button class="button" data-action="import-all">导入备份</button><input type="file" accept=".json,application/json" id="import-file" hidden><p class="support-note">导入会替换当前记录，确认前会展示内容概要。下载时请将目标文件夹选择为 D:\\codex。</p>');$('#import-file').addEventListener('change',importBackup);}
async function importBackup(e){const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('请选择小于 5 MB 的备份。');pendingImport=validate(JSON.parse(await file.text()));utility('确认恢复学习记录',`<p>包含 ${Object.values(pendingImport.notes).filter(Boolean).length} 条章节笔记、${Object.keys(pendingImport.answers).length} 道测验记录和 ${Object.keys(pendingImport.mistakes).length} 条错题。</p><p>恢复将替换当前记录，建议先导出当前版本。</p><button class="button" data-action="export-all">先备份当前记录</button><button class="button primary" data-action="confirm-import">确认替换并恢复</button>`);}catch(error){pendingImport=null;toast(error.message||'不是有效的学习备份。');}}
function search(query){const q=query.trim().toLowerCase();let hits=[];for(const l of lessons)if(!q||[l.title,l.short,l.concept,l.pitfall,...l.terms,JSON.stringify(l.cards||[]),l.code,...l.tasks.map(t=>t.prompt),...l.quizzes.map(q=>q.prompt)].join(' ').toLowerCase().includes(q))hits.push(`<a class="search-result" href="#learn/${l.id}" data-search-result><strong>${l.title}</strong><small>${l.track.toUpperCase()} · ${esc(l.lead)}</small></a>`);if(q)for(const [term,meaning] of Object.entries(glossary))if((term+meaning).toLowerCase().includes(q))hits.push(`<button class="search-result" style="width:100%;text-align:left;background:none" data-term="${term}"><strong>术语 · ${term}</strong><small>${esc(meaning)}</small></button>`);if(q)for(const g of guides)if((g.title+g.html.replace(/<[^>]+>/g,'')).toLowerCase().includes(q))hits.push(`<a class="search-result" href="#help/${g.id}" data-search-result><strong>工具救援 · ${g.title}</strong><small>${g.tag}</small></a>`);$('#search-results').innerHTML=hits.slice(0,25).join('')||'<p class="support-note">没有找到。试试「类型」「变量」或具体报错名称。</p>';}
function submitQuiz(form){const id=form.dataset.quiz,l=lessons.find(l=>l.quizzes.some(q=>q.id===id)),q=l.quizzes.find(q=>q.id===id),selected=form.querySelector('input:checked');if(!selected){toast('先选择一个答案。');return;}const n=Number(selected.value),ok=n===q.correct,old=state.answers[id];state.answers[id]={first:old?.first??ok,latest:ok,selected:n,tries:(old?.tries||0)+1,at:Date.now()};if(!ok){const previous=state.mistakes[id];state.mistakes[id]={...previous,type:'quiz',lessonId:l.id,title:q.prompt,original:previous?.original??q.options[n],resolved:false,at:Date.now()};}else if(state.mistakes[id])state.mistakes[id].resolved=true;save();if(route==='mistakes')renderMistakes();else{renderBody();const value=$$('.stat strong')[1];if(value)value.textContent=percent();const label=$$('.stat small')[1];if(label)label.textContent='最近测验正确率 · 首次 '+percent(true);}sidebar();toast(ok?'理解正确，继续保持自己的节奏。':'已加入错题本，看看解释再试一次。');}
function loadTask(id){const t=lesson.tasks.find(t=>t.id===id);if(!t)return;stop(false);activeCard=null;activeTask=t;tab='practice';renderBody();renderEditor();if(innerWidth<960)$('#editor-host').scrollIntoView({behavior:'smooth',block:'start'});toast('题目已载入实验台，修改后'+(lesson.track!=='java'?'运行并检查。':'在 VS Code 运行。'));}
document.addEventListener('submit',e=>{if(e.target.matches('[data-quiz]')){e.preventDefault();submitQuiz(e.target);}});
document.addEventListener('input',e=>{if(e.target.id==='chapter-note'){state.notes[lesson.id]=e.target.value;$('#note-status').textContent=save()?'已保存在当前浏览器 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'保存失败，请导出备份。';}});
document.addEventListener('change',e=>{if(e.target.matches('[data-goal]')){state.goals[lesson.id]??=lesson.goals.map(()=>false);state.goals[lesson.id][Number(e.target.dataset.goal)]=e.target.checked;save();}});
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a');if(!b)return;
 if(b.hasAttribute('data-close'))b.closest('dialog').close();
 if(b.hasAttribute('data-search-result'))$('#search-dialog').close();
 if(b.dataset.tab){tab=b.dataset.tab;renderBody();}
 if(b.dataset.term){if($('#search-dialog').open)$('#search-dialog').close();glossaryDialog(b.dataset.term);}
 if(b.dataset.rate){state.ratings[lesson.id]=b.dataset.rate;save();renderLearn();sidebar();toast(b.dataset.rate==='independent'?'记录好了：能独立完成。':'记录好了：练习过。随时回来巩固。');}
 if(b.dataset.filter){reviewFilter=b.dataset.filter;renderMistakes();}
 if(b.dataset.hint){const id=b.dataset.hint;hints[id]=Math.min((hints[id]||0)+1,3);state.help[id]={hints:hints[id],answer:!!seenAnswers[id]};save();renderBody();}
 if(b.dataset.answer){const id=b.dataset.answer;seenAnswers[id]=true;answerOpen[id]=!answerOpen[id];state.help[id]={hints:hints[id]||0,answer:true};save();renderBody();}
 if(b.dataset.task)loadTask(b.dataset.task);
 if(b.dataset.copyPre)copy(document.getElementById(b.dataset.copyPre).textContent);
 if(b.hasAttribute('data-card-copy'))copy(lesson.cards[Number(b.dataset.cardCopy)].code);
 if(b.hasAttribute('data-card-load')){stop(false);activeTask=null;activeCard=Number(b.dataset.cardLoad);renderEditor();$('#editor-host').scrollIntoView({behavior:'smooth',block:'start'});toast('知识点已载入，拥有独立草稿，不会覆盖主示例。');}
 if(b.hasAttribute('data-file-download')){const f=outputs[draftKey()]?.files?.[Number(b.dataset.fileDownload)];if(f)download(Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)),f.name,'application/octet-stream');}
 if(b.dataset.reviewTask){try{sessionStorage.setItem('code-first-review-task',b.dataset.reviewTask);}catch{}}
 const a=b.dataset.action;if(!a)return;
 if(a==='practice'){tab='practice';renderBody();}
 if(a==='jump-editor'){$('#editor-host').scrollIntoView({behavior:'smooth',block:'start'});$('#code-editor').focus({preventScroll:true});}
 if(a==='glossary')glossaryDialog();if(a==='copy-example')copy(lesson.code);if(a==='copy-code')copy($('#code-editor').value);if(a==='download')download($('#code-editor').value,lesson.file);
 if(a==='run')run();if(a==='stop')stop();
 if(a==='reset')utility('恢复起始代码',`<p>将用${activeTask?'这道题的起始代码':'本课示例'}替换实验台里的修改。笔记和其他题目草稿会保留。</p><button class="button primary" data-action="confirm-reset">恢复起始代码</button>`);
 if(a==='confirm-reset'){stop(false);state.drafts[draftKey()]=starter();state.inputs[draftKey()]=inputDefault();delete outputs[draftKey()];save();$('#utility-dialog').close();renderEditor();}
 if(a==='exit-example'){stop(false);activeCard=null;renderEditor();}
 if(a==='exit-task'){stop(false);activeTask=null;renderEditor();if(tab==='practice')renderBody();}
 if(a==='clear'){$('#run-artifacts').innerHTML='';delete outputs[draftKey()];$('#actual-output').textContent='输出已清空。';$('#actual-output').classList.remove('error');$('#run-feedback').innerHTML='';}
 if(a==='self-check'&&activeTask){const old=state.tasks[activeTask.id];state.tasks[activeTask.id]={first:old?.first??true,passed:true,mode:'self',at:Date.now(),message:''};save();renderBody();toast('已记录为本地自查完成。');}
 if(a==='export-note')download(`# ${lesson.title}\n\n${state.notes[lesson.id]||''}`,`${lesson.short}-笔记.md`,'text/markdown;charset=utf-8');
 if(a==='export-all')download(JSON.stringify(state,null,2),`码上起步-学习备份-${new Date().toISOString().slice(0,10)}.json`,'application/json');
 if(a==='import-all')$('#import-file').click();
 if(a==='confirm-import'&&pendingImport){stop(false);state=pendingImport;pendingImport=null;hints={};seenAnswers={};for(const [id,v] of Object.entries(state.help)){hints[id]=v.hints;seenAnswers[id]=v.answer;}answerOpen={};outputs={};activeTask=null;activeCard=null;save();theme();$('#utility-dialog').close();const target='#learn/'+state.last;if(location.hash===target)navigate();else location.hash=target;toast('学习记录已恢复。');}
});
$('#search-btn').addEventListener('click',()=>{$('#search-dialog').showModal();$('#search-input').value='';search('');$('#search-input').focus();});$('#search-input').addEventListener('input',e=>search(e.target.value));
$('#theme-btn').addEventListener('click',()=>{state.theme=document.documentElement.classList.contains('dark')?'light':'dark';theme();save();});
$('#track-select').addEventListener('change',e=>{const next=lessons.find(l=>l.track===e.target.value);if(next)location.hash='#learn/'+next.id;});
$('#menu-btn').addEventListener('click',()=>{$('#sidebar').classList.toggle('open');$('#menu-btn').setAttribute('aria-expanded',String($('#sidebar').classList.contains('open')));});$('#backup-btn').addEventListener('click',backup);
$('.skip').addEventListener('click',e=>{e.preventDefault();$('#main').focus();});
document.addEventListener('click',e=>{if($('#sidebar').classList.contains('open')&&!e.target.closest('#sidebar,#menu-btn'))$('#sidebar').classList.remove('open');});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.target.matches('input,textarea')&&!$('dialog[open]')){e.preventDefault();$('#search-btn').click();}if(e.key==='Escape')$('#sidebar').classList.remove('open');if(e.target.matches('[role=tab]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=$$('[role=tab]'),i=tabs.indexOf(e.target),next=tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.click();next.focus();}});
for(const event of ['pointerdown','keydown','scroll'])document.addEventListener(event,()=>{lastActivity=Date.now();},{passive:true});
setInterval(()=>{if(!document.hidden&&Date.now()-lastActivity<120000&&document.hasFocus()){state.seconds+=10;save();const c=$$('.stat strong')[2];if(c)c.innerHTML=Math.floor(state.seconds/60)+'<span>分钟</span>';}},10000);
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{state=validate(JSON.parse(e.newValue));theme();sidebar();}catch{}}});
window.addEventListener('hashchange',()=>{navigate();try{const id=sessionStorage.getItem('code-first-review-task');if(id&&route==='learn'){sessionStorage.removeItem('code-first-review-task');loadTask(id);}}catch{}});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.theme==='system')theme();});
theme();navigate();if(storageError)toast('之前的记录无法读取。可以继续学习，请使用备份功能。');
// Feature-detect WebMCP. Navigation never claims exercise completion.
const lifecycle=new AbortController();
if(document.modelContext?.registerTool){
 const tools=[{name:'get_learning_progress',title:'读取学习进度',description:'读取当前浏览器的课程状态与待复习数量，不修改记录。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({lessons:lessons.map(l=>({id:l.id,title:l.title,status:status(l)})),pendingMistakes:pending(),minutes:Math.floor(state.seconds/60)})},{name:'open_learning_lesson',title:'打开课程',description:'打开已有课程并记录接触过，不标记练习通过或独立完成。',inputSchema:{type:'object',properties:{lessonId:{type:'string',enum:lessons.map(l=>l.id)}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input.lessonId!=='string'||Object.keys(input).some(k=>k!=='lessonId')||!lessons.some(l=>l.id===input.lessonId))throw Error('请选择有效课程 ID。');const target='#learn/'+input.lessonId;if(location.hash===target)navigate();else{location.hash=target;await new Promise(resolve=>window.addEventListener('hashchange',resolve,{once:true}));}return {lessonId:lesson.id,title:lesson.title};}}];
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

function knowledgeCards(){return lesson.cards?.length?`<section class="knowledge-stack"><h2>接着学 · 每次展开一个</h2><p class="support-note">每个示例都能单独运行。「选学」可以先跳过。</p>${lesson.cards.map((c,i)=>`<details class="knowledge-card"><summary>${c.optional?'<span class="tag">选学</span> ':''}${esc(c.title)}</summary><p class="body-copy"><strong>是什么：</strong>${esc(c.concept)}</p><div class="analogy"><strong>为什么 · 你可以这样想</strong>${esc(c.analogy)}</div><div class="code-example"><div class="code-head">PYTHON<button class="text-button" data-card-copy="${i}">复制</button></div><pre>${highlight(c.code)}</pre></div><div class="output-example"><span>预期输出 · 运行后请核对</span><pre>${esc(c.expected)}</pre></div><div class="pitfall"><strong>易错点</strong><br>${esc(c.pitfall)}</div><button class="button primary" data-card-load="${i}">载入实验台</button></details>`).join('')}</section>`:'';}
function artifacts(out){if(!out)return '';return (out.figures?.length?`<section class="plot-results"><h3>生成的图表</h3>${out.figures.map((png,i)=>`<figure><img src="data:image/png;base64,${png}" alt="本次 Python 程序生成的图表 ${i+1}"><figcaption>图 ${i+1} · 实际运行结果 <a class="text-button" download="figure-${i+1}.png" href="data:image/png;base64,${png}">下载 PNG</a></figcaption></figure>`).join('')}</section>`:'')+(out.files?.length?`<section class="file-results"><h3>本次生成 / 更新的文件</h3>${out.files.map((f,i)=>`<button class="button" data-file-download="${i}">${esc(f.name)} · ${Math.ceil(f.size/1024)} KB ↓</button>`).join('')}<p class="support-note">文件在浏览器临时区。下载时请选 D:\\codex；刷新或停止运行可能清空临时文件。每次最多展示 10 个文件，每个 ≤3 MB。</p></section>`:'')+(Object.keys(out.versions||{}).length?`<p class="runtime-help">本次环境：${Object.entries(out.versions).map(([k,v])=>esc(k+' '+v)).join(' · ')}<br>最多预览 4 张静态图。中文字体未预装时请使用英文标签，或下载代码在本地运行。</p>`:'');}
function dataRoadmap(){return `<section class="panel list-card data-intro"><span class="tag">NEW · 数据分析路线</span><h2>让一份表格，变成一个看得懂的结果。</h2><p>前置：Python 变量、列表、条件、函数和导入。建议每次只学一张知识卡，20 分钟章节可以分几次完成。</p><div class="diagram"><span class="diagram-box">NumPy · 数组计算</span> → <span class="diagram-box">Pandas · 表格处理</span> → <span class="diagram-box">Matplotlib · 画图</span> → <span class="diagram-box">综合项目</span></div><p class="support-note">这是学习顺序。依赖关系：Pandas 和 Matplotlib 都使用 NumPy；Pandas 默认绘图会调用 Matplotlib，Matplotlib 也能直接使用数组。</p><a class="button primary" href="#learn/np-create">开始数据分析第一课</a><a class="button" href="#help/science">本地环境与进阶工具</a></section>${['numpy','pandas','matplotlib','analysis'].map(track=>`<section class="map-section"><div class="map-header"><span class="track-number">${track==='numpy'?'N':track==='pandas'?'P':track==='matplotlib'?'M':'D'}</span><div><h2>${tracks[track]}</h2><p>例子 → 修改 → 独立练习 → 检查理解</p></div></div><div class="course-grid">${lessons.filter(l=>l.track===track).map(l=>`<a class="course-card" href="#learn/${l.id}"><span class="tag">${l.chapter} · ${l.optional?'选学':'基础与实用'}</span><h3>${esc(l.title)}</h3><p>${esc(l.lead)}</p><small><span>约 ${l.minutes} 分钟 · 可分次</span><span>${status(l)}</span></small></a>`).join('')}</div></section>`).join('')}`;}
